### ISSUE TITLE
Loading DuckDuckGo crashes Servo

### ISSUE THREAD

**Issue by atouchet** [servo/servo#19348]
Steps to reproduce:

1. Run Servo.
2. Load https://duckduckgo.com/
3. Servo will crash before the page finishes loading. The Servo window closes and the Browser.html issue reporter does not appear.

This is a new regression as this crash did not occur in previous nightly builds. Tested in Windows 10 with Browser.html.

**Comment by atouchet** [comment]
This issue does not appear to occur with the https://duckduckgo.com/html/ version of the site. https://arstechnica.com/ also crashes similarly in the latest build. I am not sure if that is due to the same issue or not.

**Comment by jdm** [comment]
Wow, that's a new one:
```
Assertion failure: false (pn->pn_scopecoord.set(parser->tokenStream, hops, *slot)), at /Users/jdm/src/master-servo/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.50.0/mozjs/js/src/frontend/BytecodeEmitter.cpp:1732
Stack trace for thread "ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(NonZero(NonZero(1))) }"
stack backtrace:
   0:        0x111cfe6fc - backtrace::backtrace::trace<closure>
                        at .cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.2/src/backtrace/mod.rs:42
   1:        0x111cfe79f - backtrace::capture::Backtrace::new::ha9cf2d44e00d2e11
                        at .cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.2/src/capture.rs:64
   2:        0x10de45b04 - servo::install_crash_handler::handler
                        at ports/servo/main.rs:72
   3:     0x7fff97a57b39 - _sigtramp
   4:        0x113f30532 - js::frontend::BytecodeEmitter::tryConvertFreeName(js::frontend::ParseNode*)
                        at /Users/jdm/src/master-servo/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.50.0/mozjs/js/src/frontend/BytecodeEmitter.cpp:1732
   5:        0x113f30ddc - js::frontend::BytecodeEmitter::bindNameToSlotHelper(js::frontend::ParseNode*)
                        at /Users/jdm/src/master-servo/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.50.0/mozjs/js/src/frontend/BytecodeEmitter.cpp:1872
   6:        0x113f3176e - js::frontend::BytecodeEmitter::bindNameToSlot(js::frontend::ParseNode*)
                        at /Users/jdm/src/master-servo/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.50.0/mozjs/js/src/frontend/BytecodeEmitter.cpp:2045
   7:        0x113f33f15 - js::frontend::BytecodeEmitter::emitNameOp(js::frontend::ParseNode*, bool)
                        at /Users/jdm/src/master-servo/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.50.0/mozjs/js/src/frontend/BytecodeEmitter.cpp:2697
   8:        0x113f22a4d - js::frontend::BytecodeEmitter::emitTree(js::frontend::ParseNode*, js::frontend::BytecodeEmitter::EmitLineNumberNote)
                        at /Users/jdm/src/master-servo/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.50.0/mozjs/js/src/frontend/BytecodeEmitter.cpp:9070
   9:        0x113f342c3 - js::frontend::BytecodeEmitter::emitPropLHS(js::frontend::ParseNode*)
                        at /Users/jdm/src/master-servo/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.50.0/mozjs/js/src/frontend/BytecodeEmitter.cpp:2760
  10:        0x113f3456e - js::frontend::BytecodeEmitter::emitPropOp(js::frontend::ParseNode*, JSOp)
                        at /Users/jdm/src/master-servo/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.50.0/mozjs/js/src/frontend/BytecodeEmitter.cpp:2797
  11:        0x113f48bf1 - js::frontend::BytecodeEmitter::emitCallOrNew(js::frontend::ParseNode*)
                        at /Users/jdm/src/master-servo/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.50.0/mozjs/js/src/frontend/BytecodeEmitter.cpp:7651
  12:        0x113f225f1 - js::frontend::BytecodeEmitter::emitTree(js::frontend::ParseNode*, js::frontend::BytecodeEmitter::EmitLineNumberNote)
                        at /Users/jdm/src/master-servo/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.50.0/mozjs/js/src/frontend/BytecodeEmitter.cpp:8986
  13:        0x113f4597a - js::frontend::BytecodeEmitter::emitReturn(js::frontend::ParseNode*)
                        at /Users/jdm/src/master-servo/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.50.0/mozjs/js/src/frontend/BytecodeEmitter.cpp:6929
  14:        0x113f22133 - js::frontend::BytecodeEmitter::emitTree(js::frontend::ParseNode*, js::frontend::BytecodeEmitter::EmitLineNumberNote)
                        at /Users/jdm/src/master-servo/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.50.0/mozjs/js/src/frontend/BytecodeEmitter.cpp:8816
  15:        0x113f47014 - js::frontend::BytecodeEmitter::emitStatementList(js::frontend::ParseNode*)
                        at /Users/jdm/src/master-servo/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.50.0/mozjs/js/src/frontend/BytecodeEmitter.cpp:7209
  16:        0x113f221e8 - js::frontend::BytecodeEmitter::emitTree(js::frontend::ParseNode*, js::frontend::BytecodeEmitter::EmitLineNumberNote)
                        at /Users/jdm/src/master-servo/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.50.0/mozjs/js/src/frontend/BytecodeEmitter.cpp:8836
  17:        0x113f4bf0d - js::frontend::BytecodeEmitter::emitArgsBody(js::frontend::ParseNode*)
                        at /Users/jdm/src/master-servo/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.50.0/mozjs/js/src/frontend/BytecodeEmitter.cpp:8515
  18:        0x113f21eef - js::frontend::BytecodeEmitter::emitTree(js::frontend::ParseNode*, js::frontend::BytecodeEmitter::EmitLineNumberNote)
                        at /Users/jdm/src/master-servo/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.50.0/mozjs/js/src/frontend/BytecodeEmitter.cpp:8751
  19:        0x113f2550c - js::frontend::BytecodeEmitter::emitFunctionScript(js::frontend::ParseNode*)
                        at /Users/jdm/src/master-servo/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.50.0/mozjs/js/src/frontend/BytecodeEmitter.cpp:3739
  20:        0x113f2667e - js::frontend::CompileLazyFunction(JSContext*, JS::Handle<js::LazyScript*>, char16_t const*, unsigned long)
                        at /Users/jdm/src/master-servo/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.50.0/mozjs/js/src/frontend/BytecodeCompiler.cpp:868
  21:        0x113aabb5c - JSFunction::createScriptForLazilyInterpretedFunction(JSContext*, JS::Handle<JSFunction*>)
                        at /Users/jdm/src/master-servo/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.50.0/mozjs/js/src/jsfun.cpp:1512
  22:        0x1139cdae2 - JSFunction::getOrCreateScript(JSContext*)
                        at /Users/jdm/src/master-servo/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.50.0/mozjs/js/src/jsfun.h:422
  23:        0x113c8cd06 - Interpret(JSContext*, js::RunState&)
                        at /Users/jdm/src/master-servo/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.50.0/mozjs/js/src/vm/Interpreter.cpp:2885
  24:        0x113c81ff8 - js::RunScript(JSContext*, js::RunState&)
                        at /Users/jdm/src/master-servo/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.50.0/mozjs/js/src/vm/Interpreter.cpp:399
  25:        0x113c98caa - js::ExecuteKernel(JSContext*, JS::Handle<JSScript*>, JSObject&, JS::Value const&, js::AbstractFramePtr, JS::Value*)
                        at /Users/jdm/src/master-servo/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.50.0/mozjs/js/src/vm/Interpreter.cpp:679
  26:        0x113c99202 - js::Execute(JSContext*, JS::Handle<JSScript*>, JSObject&, JS::Value*)
                        at /Users/jdm/src/master-servo/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.50.0/mozjs/js/src/vm/Interpreter.cpp:711
  27:        0x1139cf52f - Evaluate(JSContext*, JS::Handle<JSObject*>, JS::Handle<js::StaticScope*>, JS::ReadOnlyCompileOptions const&, JS::SourceBufferHolder&, JS::MutableHandle<JS::Value>)
                        at /Users/jdm/src/master-servo/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.50.0/mozjs/js/src/jsapi.cpp:4406
  28:        0x1139cf79d - Evaluate(JSContext*, JS::ReadOnlyCompileOptions const&, char16_t const*, unsigned long, JS::MutableHandle<JS::Value>)
                        at /Users/jdm/src/master-servo/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.50.0/mozjs/js/src/jsapi.cpp:4443
  29:        0x1139cf68c - JS::Evaluate(JSContext*, JS::ReadOnlyCompileOptions const&, char16_t const*, unsigned long, JS::MutableHandle<JS::Value>)
                        at /Users/jdm/src/master-servo/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.50.0/mozjs/js/src/jsapi.cpp:4501
  30:        0x1113917aa - script::dom::globalscope::{{impl}}::evaluate_script_on_global_with_result::{{closure}}
                        at components/script/dom/globalscope.rs:414
  31:        0x110c77760 - profile_traits::time::profile<bool,closure>
                        at /Users/jdm/src/master-servo/components/profile_traits/time.rs:125
  32:        0x111391353 - script::dom::globalscope::GlobalScope::evaluate_script_on_global_with_result::h392945caf5cb5634
                        at components/script/dom/globalscope.rs:398
  33:        0x1113e66b9 - script::dom::htmlscriptelement::HTMLScriptElement::run_a_classic_script::h6e754542d2cc22e0
                        at components/script/dom/htmlscriptelement.rs:569
  34:        0x1113e6023 - script::dom::htmlscriptelement::HTMLScriptElement::execute::h34a2d72e24635b7f
                        at components/script/dom/htmlscriptelement.rs:539
  35:        0x11146348d - script::dom::servoparser::ServoParser::resume_with_pending_parsing_blocking_script::hb48f17896d05e854
                        at components/script/dom/servoparser/mod.rs:226
  36:        0x1108af4ba - script::dom::document::{{impl}}::process_pending_parsing_blocking_script
                        at components/script/dom/document.rs:1746
  37:        0x1108af1a2 - script::dom::document::Document::pending_parsing_blocking_script_loaded::h3a0cf683523f7a6a
                        at components/script/dom/document.rs:1733
  38:        0x1113e15d4 - _$LT$script..dom..htmlscriptelement..ScriptContext$u20$as$u20$net_traits..FetchResponseListener$GT$::process_response_eof::he653eda2b89d2c95
                        at components/script/dom/htmlscriptelement.rs:218
  39:        0x1110f53a9 - net_traits::{{impl}}::process<script::dom::htmlscriptelement::ScriptContext>
                        at /Users/jdm/src/master-servo/components/net_traits/lib.rs:249
  40:        0x1114c9aab - script::network_listener::{{impl}}::run_once<net_traits::FetchResponseMsg,script::dom::htmlscriptelement::ScriptContext>
                        at components/script/network_listener.rs:66
  41:        0x1107fbf18 - script::task::{{impl}}::run_once<script::network_listener::ListenerTask<net_traits::FetchResponseMsg, script::dom::htmlscriptelement::ScriptContext>>
                        at components/script/task.rs:116
  42:        0x1107f6d45 - script::task::{{impl}}::run_box<script::task::CancellableTask<script::network_listener::ListenerTask<net_traits::FetchResponseMsg, script::dom::htmlscriptelement::ScriptContext>>>
                        at components/script/task.rs:60
  43:        0x110937580 - script::script_thread::{{impl}}::handle_msg_from_script
                        at components/script/script_thread.rs:1345
  44:        0x110931847 - script::script_thread::{{impl}}::handle_msgs::{{closure}}
                        at components/script/script_thread.rs:1072
  45:        0x11093503c - script::script_thread::{{impl}}::profile_event<closure,core::option::Option<bool>>
                        at components/script/script_thread.rs:1245
  46:        0x11092f73f - script::script_thread::{{impl}}::handle_msgs
                        at components/script/script_thread.rs:1065
  47:        0x11092d597 - script::script_thread::ScriptThread::start::h41c49a191a84dee3
                        at components/script/script_thread.rs:897
  48:        0x110928fd4 - script::script_thread::{{impl}}::create::{{closure}}::{{closure}}
                        at components/script/script_thread.rs:578
  49:        0x110c75cae - profile_traits::mem::{{impl}}::run_with_memory_reporting<closure,fn(profile_traits::mem::ReportsChan) -> script::script_runtime::CommonScriptMsg,script::script_runtime::CommonScriptMsg,std::sync::mpsc::Sender<script::script_thread::MainThreadScriptMsg>>
                        at /Users/jdm/src/master-servo/components/profile_traits/mem.rs:63
  50:        0x1109295ed - script::script_thread::{{impl}}::create::{{closure}}
                        at components/script/script_thread.rs:577
  51:        0x110dea354 - std::sys_common::backtrace::__rust_begin_short_backtrace<closure,()>
                        at /Users/travis/build/rust-lang/rust/src/libstd/sys_common/backtrace.rs:133
  52:        0x110e51a3b - std::thread::{{impl}}::spawn::{{closure}}::{{closure}}<closure,()>
                        at /Users/travis/build/rust-lang/rust/src/libstd/thread/mod.rs:406
  53:        0x10fd3c2c4 - std::panic::{{impl}}::call_once<(),closure>
                        at /Users/travis/build/rust-lang/rust/src/libstd/panic.rs:300
  54:        0x10ff2b674 - std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure>,()>
                        at /Users/travis/build/rust-lang/rust/src/libstd/panicking.rs:480
  55:        0x11424612e - __rust_maybe_catch_panic
                        at src/libpanic_unwind/lib.rs:99
  56:        0x10fed023c - std::panicking::try<(),std::panic::AssertUnwindSafe<closure>>
                        at /Users/travis/build/rust-lang/rust/src/libstd/panicking.rs:459
  57:        0x10fd8f94c - std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure>,()>
                        at /Users/travis/build/rust-lang/rust/src/libstd/panic.rs:365
  58:        0x110e5130d - std::thread::{{impl}}::spawn::{{closure}}<closure,()>
                        at /Users/travis/build/rust-lang/rust/src/libstd/thread/mod.rs:405
  59:        0x110f290d5 - alloc::boxed::{{impl}}::call_box<(),closure>
                        at /Users/travis/build/rust-lang/rust/src/liballoc/boxed.rs:762
  60:        0x114239feb - std::sys::imp::thread::{{impl}}::new::thread_start
                        at src/libstd/sys_common/thread.rs:23
  61:     0x7fff97a6193a - _pthread_body
  62:     0x7fff97a61886 - _pthread_start
```

**Comment by jdm** [comment]
Arstechnica.com now fails with the same crash. I'm really curious about when this started happening...

**Comment by jdm** [comment]
Strangely enough, this is a regression from #19225. cc @nox

**Comment by nox** [comment]
Could it be some linking issue again? @cpearce @philn Does the stacktrace look like something that could happen with wrong duplicate symbols between mozjs_sys and gecko-media?

**Comment by jdm** [comment]
More specifically, the problem is first introduced in 38fd9648ce48907f3baffc66ff0e1f2e25690d4e.

**Comment by philn** [comment]
At first glance this doesn't look like a duplicate symbol issue between mozjs_sys and gecko-media.

**Comment by jdm** [comment]
More specifically, it is merely the addition of the code in the constellation that causes this crash to appear. The update to gecko-media does not affect it.

**Comment by bobthekingofegypt** [comment]
If it helps any, https://github.com/servo/servo/commit/38fd9648ce48907f3baffc66ff0e1f2e25690d4e is part of the changeset that fixed my every webpage crashing issue, https://github.com/servo/servo/issues/19299

Also I can load https://duckduckgo.com without issue using master, I cannot load arstechnica but for a different reason to jdm; I get this https://github.com/servo/webrender/issues/2093 bug.

**Comment by jdm** [comment]
I cannot reproduce this in my Ubuntu VM; I continue to reproduce this on my macOS build.

**Comment by atouchet** [comment]
I am able to load DuckDuckGo without it crashing in the latest nightly build using Windows 10.

**Comment by atouchet** [comment]
@jdm are you still able to reproduce this? I haven't run into this crash in the last couple of days.

**Comment by jdm** [comment]
I've been investigating using a build from 6d49ec83a15f440f85cb9a045eaf104f30bd3053, which still reproduces it consistently. I haven't tried anything more recent yet, but I can continue to reproduce with this minimized version of gecko-media: https://github.com/jdm/fake-gecko-media

```
[patch."https://github.com/servo/gecko-media.git"]
gecko-media = { path = "../fake-gecko-media" }
```

**Comment by jdm** [comment]
I just checked and I can still reproduce this problem on master.

**Comment by jdm** [comment]
jrmuizel connected the missing pieces for me - mozjs and gecko-media both include vendored copies of mfbt (which is a header-only library), and this violates the [one definition rule](https://en.wikipedia.org/wiki/One_Definition_Rule). Rust avoids this problem through including hashes in the symbol names, which allows projects to include multiple versions of the same library without encountering conflicts. We need to either:
* rename all conflicting symbols
* make both mozjs and gecko-media share the same copy of mfbt (and mozglue, and mozalloc, etc.)
* find a way to instruct the build system to not export the non-extern symbols so the conflicts do not arise

**Comment by nox** [comment]
The gecko-media PR has yet to land in servo/servo.
