### ISSUE TITLE
Link failure on linux64: error: undefined reference to '_$LT$script..dom..bindings..js..Root$LT$T$GT$$GT$::downcast::h91b0ac4007c4c9f0'

### ISSUE THREAD

**Issue by bholley** [servo/servo#14916]
After rebasing this weekend, I started getting the following link failure building servo:

   Compiling layout_thread v0.0.1 (file:///files/mozilla/servo/b/components/layout_thread)
   Compiling libservo v0.0.1 (file:///files/mozilla/servo/b/components/servo)
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" "/files/mozilla/servo/b/.servo/rust/2017-01-06/rustc-nightly-x86_64-unknown-linux-gnu/rustc/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/files/mozilla/servo/b/target/debug/deps/servo-b997425f6fb0a6f8.0.o" "/files/mozilla/servo/b/target/debug/deps/servo-b997425f6fb0a6f8.1.o" "/files/mozilla/servo/b/target/debug/deps/servo-b997425f6fb0a6f8.10.o" "/files/mozilla/servo/b/target/debug/deps/servo-b997425f6fb0a6f8.11.o" "/files/mozilla/servo/b/target/debug/deps/servo-b997425f6fb0a6f8.12.o" "/files/mozilla/servo/b/target/debug/deps/servo-b997425f6fb0a6f8.13.o" "/files/mozilla/servo/b/target/debug/deps/servo-b997425f6fb0a6f8.14.o" "/files/mozilla/servo/b/target/debug/deps/servo-b997425f6fb0a6f8.15.o" "/files/mozilla/servo/b/target/debug/deps/servo-b997425f6fb0a6f8.2.o" "/files/mozilla/servo/b/target/debug/deps/servo-b997425f6fb0a6f8.3.o" "/files/mozilla/servo/b/target/debug/deps/servo-b997425f6fb0a6f8.4.o" "/files/mozilla/servo/b/target/debug/deps/servo-b997425f6fb0a6f8.5.o" "/files/mozilla/servo/b/target/debug/deps/servo-b997425f6fb0a6f8.6.o" "/files/mozilla/servo/b/target/debug/deps/servo-b997425f6fb0a6f8.7.o" "/files/mozilla/servo/b/target/debug/deps/servo-b997425f6fb0a6f8.8.o" "/files/mozilla/servo/b/target/debug/deps/servo-b997425f6fb0a6f8.9.o" "-o" "/files/mozilla/servo/b/target/debug/deps/servo-b997425f6fb0a6f8" "-Wl,--gc-sections" "-pie" "-nodefaultlibs" "-L" "/files/mozilla/servo/b/target/debug/deps" "-L" "/usr/lib/x86_64-linux-gnu" "-L" "/usr/lib/x86_64-linux-gnu" "-L" "/files/mozilla/servo/b/target/debug/build/miniz-sys-428121ff932ec089/out" "-L" "/files/mozilla/servo/b/target/debug/build/openssl-87c538093dbe2342/out" "-L" "/usr/lib/x86_64-linux-gnu" "-L" "/files/mozilla/servo/b/target/debug/build/openssl-sys-extras-45159e42f4e1f90d/out" "-L" "/files/mozilla/servo/b/target/debug/build/servo-freetype-sys-28eb503339d71bb6/out/lib" "-L" "/files/mozilla/servo/b/target/debug/build/tinyfiledialogs-60b88f151d28bc60/out" "-L" "/usr/lib/x86_64-linux-gnu" "-L" "/usr/lib/x86_64-linux-gnu" "-L" "/usr/lib/x86_64-linux-gnu" "-L" "/files/mozilla/servo/b/target/debug/build/fontsan-58f875ff64dc5050/out/lib" "-L" "/files/mozilla/servo/b/target/debug/build/js-c64f072da51ed063/out/lib" "-L" "/files/mozilla/servo/b/target/debug/build/mozjs_sys-365f6a67e79262dc/out/js/src" "-L" "/usr/lib/x86_64-linux-gnu" "-L" "/files/mozilla/servo/b/target/debug/build/angle-d19bfa9b021b1b83/out" "-L" "/files/mozilla/servo/b/target/debug/build/azure-e3c1f38043b54744/out/lib" "-L" "/files/mozilla/servo/b/target/debug/build/servo-skia-37e601268e2c679c/out/lib" "-L" "/files/mozilla/servo/b/target/debug/build/heartbeats-simple-sys-d27efab335cf580d/out/lib" "-L" "/usr/lib/x86_64-linux-gnu" "-L" "/files/mozilla/servo/b/.servo/rust/2017-01-06/rustc-nightly-x86_64-unknown-linux-gnu/rustc/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "-Wl,-Bdynamic" "/files/mozilla/servo/b/target/debug/deps/libservo-38cedad766383a68.rlib" "/files/mozilla/servo/b/target/debug/deps/liblayout_thread-43d02f1a4d1a43fe.rlib" "/files/mozilla/servo/b/target/debug/deps/libnet-8ee77dd3a087a0ad.rlib" "/files/mozilla/servo/b/target/debug/deps/libbluetooth-9be03449a1b41366.rlib" "/files/mozilla/servo/b/target/debug/deps/libscript-2203cc0d1eeee2a4.rlib" "/files/mozilla/servo/b/target/debug/deps/libref_slice-12432743682c7d01.rlib" "/files/mozilla/servo/b/target/debug/deps/libmime_guess-6487aec7fc551a68.rlib" "/files/mozilla/servo/b/target/debug/deps/libcaseless-a3e0c3b3ae1de2f9.rlib" "/files/mozilla/servo/b/target/debug/deps/libaudio_video_metadata-41247838c61c0c62.rlib" "/files/mozilla/servo/b/target/debug/deps/libmp4parse-74a3f827333a8ea8.rlib" "/files/mozilla/servo/b/target/debug/deps/libglutin_app-934df6d862e4ebee.rlib" "/files/mozilla/servo/b/target/debug/deps/libcontent_blocker-5d999189e4e065c5.rlib" "/files/mozilla/servo/b/target/debug/deps/libdevtools-f01b47130f4c6990.rlib" "/files/mozilla/servo/b/target/debug/deps/libenv_logger-1fc32eeb74e9a4d9.rlib" "/files/mozilla/servo/b/target/debug/deps/libogg_metadata-8eed09e7633b5d80.rlib" "/files/mozilla/servo/b/target/debug/deps/libopen-7c7af7e18f1dc1c5.rlib" "/files/mozilla/servo/b/target/debug/deps/liblayout-347ff63202f09818.rlib" "/files/mozilla/servo/b/target/debug/deps/libbrotli-7e12fa05b197ff7f.rlib" "/files/mozilla/servo/b/target/debug/deps/libmp3_metadata-4d8c7f0f17d75513.rlib" "/files/mozilla/servo/b/target/debug/deps/libprofile-9a0da4fdab100d1f.rlib" "/files/mozilla/servo/b/target/debug/deps/libheartbeats_simple-31438d6813885313.rlib" "/files/mozilla/servo/b/target/debug/deps/libheartbeats_simple_sys-1b9ff61fad93f7e9.rlib" "/files/mozilla/servo/b/target/debug/deps/libdevice-7c0471840a1e1814.rlib" "/files/mozilla/servo/b/target/debug/deps/libblurz-786eb944af617224.rlib" "/files/mozilla/servo/b/target/debug/deps/libdbus-875d24d2fb7742db.rlib" "/files/mozilla/servo/b/target/debug/deps/libhtml5ever-9bf4b2d530f692cf.rlib" "/files/mozilla/servo/b/target/debug/deps/libconstellation-4a51ae2c89581ca8.rlib" "/files/mozilla/servo/b/target/debug/deps/libservo_rand-68a090112b78597b.rlib" "/files/mozilla/servo/b/target/debug/deps/liblayout_traits-08da8903f42af51c.rlib" "/files/mozilla/servo/b/target/debug/deps/libdebugger-fd4c40effae4a32f.rlib" "/files/mozilla/servo/b/target/debug/deps/libws-512cfa287f29a50c.rlib" "/files/mozilla/servo/b/target/debug/deps/libsha1-7c70cc5fe60809e5.rlib" "/files/mozilla/servo/b/target/debug/deps/libcompositing-c9a2121a6c61f576.rlib" "/files/mozilla/servo/b/target/debug/deps/libcanvas-fe3f469530980c7c.rlib" "/files/mozilla/servo/b/target/debug/deps/libazure-8ed9d6593b23b835.rlib" "/files/mozilla/servo/b/target/debug/deps/libskia-cf38d27370de85fd.rlib" "/files/mozilla/servo/b/target/debug/deps/libglx-bf8276b37ee12855.rlib" "/files/mozilla/servo/b/target/debug/deps/libbacktrace-2e89ef56ad5b633f.rlib" "/files/mozilla/servo/b/target/debug/deps/librustc_demangle-119a8cb112ced5ba.rlib" "/files/mozilla/servo/b/target/debug/deps/libdbghelp-a3351d69680f966f.rlib" "/files/mozilla/servo/b/target/debug/deps/libxml5ever-653b5d3f1a2050ef.rlib" "/files/mozilla/servo/b/target/debug/deps/libtendril-05cfbf41f5acfa03.rlib" "/files/mozilla/servo/b/target/debug/deps/libutf8-d21c74c8368407b8.rlib" "/files/mozilla/servo/b/target/debug/deps/libsig-632f96aa23c1592e.rlib" "/files/mozilla/servo/b/target/debug/deps/libangle-9ccd1cb74d808f61.rlib" "/files/mozilla/servo/b/target/debug/deps/libtinyfiledialogs-871aaa0adf2e9e36.rlib" "/files/mozilla/servo/b/target/debug/deps/libjs-96bd5f895d7c3853.rlib" "/files/mozilla/servo/b/target/debug/deps/libmozjs_sys-60ebc938db5aadf0.rlib" "/files/mozilla/servo/b/target/debug/deps/liblibz_sys-fb69246a610b616d.rlib" "/files/mozilla/servo/b/target/debug/deps/libimmeta-43b4eee54879121b.rlib" "/files/mozilla/servo/b/target/debug/deps/libarrayvec-e434a760ea657ee4.rlib" "/files/mozilla/servo/b/target/debug/deps/libserde_json-99385da38ca59b91.rlib" "/files/mozilla/servo/b/target/debug/deps/libdtoa-d8f1f341c06f4f43.rlib" "/files/mozilla/servo/b/target/debug/deps/libitoa-64ca65e744a0e081.rlib" "/files/mozilla/servo/b/target/debug/deps/libgaol-dca00775ea1eb476.rlib" "/files/mozilla/servo/b/target/debug/deps/libogg-4a6c4f6ac3f41f68.rlib" "/files/mozilla/servo/b/target/debug/deps/libkernel32-7cda898cd53d6f66.rlib" "/files/mozilla/servo/b/target/debug/deps/libref_filter_map-11fe5f1454cddb32.rlib" "/files/mozilla/servo/b/target/debug/deps/libgfx-7336f443bb90bf09.rlib" "/files/mozilla/servo/b/target/debug/deps/libxi_unicode-839908315dd49ffa.rlib" "/files/mozilla/servo/b/target/debug/deps/libunicode_script-27fb3e5f3f9ed398.rlib" "/files/mozilla/servo/b/target/debug/deps/libharfbuzz_sys-cff08cd4dcb2816f.rlib" "/files/mozilla/servo/b/target/debug/deps/libfontsan-35a041b0cc9bd8c6.rlib" "/files/mozilla/servo/b/target/debug/deps/libfontconfig-fc5a774acee6ae04.rlib" "/files/mozilla/servo/b/target/debug/deps/libfontconfig_sys-105762d101907e02.rlib" "/files/mozilla/servo/b/target/debug/deps/libexpat_sys-41e93882a30bf06f.rlib" "/files/mozilla/servo/b/target/debug/deps/libwebdriver_server-7cd7437ee893eda3.rlib" "/files/mozilla/servo/b/target/debug/deps/libwebdriver-6b1d356bb8d83f11.rlib" "/files/mozilla/servo/b/target/debug/deps/libsimd-5ffb36453faca85e.rlib" "/files/mozilla/servo/b/target/debug/deps/libwebrender-84fa51a0db67c528.rlib" "/files/mozilla/servo/b/target/debug/deps/libthreadpool-5b8a432a6061bc7d.rlib" "/files/mozilla/servo/b/target/debug/deps/libfreetype-b84c860146deaa98.rlib" "/files/mozilla/servo/b/target/debug/deps/libfreetype_sys-6be50884a2dfd7f1.rlib" "/files/mozilla/servo/b/target/debug/deps/libscript_layout_interface-c1e046d0359f93a9.rlib" "/files/mozilla/servo/b/target/debug/deps/libstyle-01a6a5784a655b19.rlib" "/files/mozilla/servo/b/target/debug/deps/libunicode_segmentation-1400e9f38485b222.rlib" "/files/mozilla/servo/b/target/debug/deps/libquickersort-c28beee67dd8ff78.rlib" "/files/mozilla/servo/b/target/debug/deps/libnodrop-8e16f84a499c8feb.rlib" "/files/mozilla/servo/b/target/debug/deps/libodds-410995a0b1945c7f.rlib" "/files/mozilla/servo/b/target/debug/deps/libphf-e408fc3a8e1ed1df.rlib" "/files/mozilla/servo/b/target/debug/deps/libparking_lot-ae163444ac221fd0.rlib" "/files/mozilla/servo/b/target/debug/deps/libparking_lot_core-2eca866225de185a.rlib" "/files/mozilla/servo/b/target/debug/deps/libsmallvec-589db7748298981f.rlib" "/files/mozilla/servo/b/target/debug/deps/libordered_float-b0bced31db0a7360.rlib" "/files/mozilla/servo/b/target/debug/deps/libservo_atoms-214d8f7fad844b5b.rlib" "/files/mozilla/servo/b/target/debug/deps/libselectors-e7f3d29abb6d0ef2.rlib" "/files/mozilla/servo/b/target/debug/deps/libfnv-f6865b85e5c83d50.rlib" "/files/mozilla/servo/b/target/debug/deps/libscript_traits-8f3350d755fc4527.rlib" "/files/mozilla/servo/b/target/debug/deps/libstyle_traits-de877566aabb2995.rlib" "/files/mozilla/servo/b/target/debug/deps/libdevtools_traits-97e71382c7d891fb.rlib" "/files/mozilla/servo/b/target/debug/deps/libbluetooth_traits-53c199bd9915567f.rlib" "/files/mozilla/servo/b/target/debug/deps/libregex-b87cd1b2417f0b56.rlib" "/files/mozilla/servo/b/target/debug/deps/libutf8_ranges-ff1f7ad9d4bf7e02.rlib" "/files/mozilla/servo/b/target/debug/deps/libregex_syntax-a1691e580add96f0.rlib" "/files/mozilla/servo/b/target/debug/deps/libthread_local-0553d3d1a0a49a55.rlib" "/files/mozilla/servo/b/target/debug/deps/libaho_corasick-8d866fbdac670156.rlib" "/files/mozilla/servo/b/target/debug/deps/libmemchr-667106a0439c1c44.rlib" "/files/mozilla/servo/b/target/debug/deps/libprofile_traits-513acba0cbbabe0a.rlib" "/files/mozilla/servo/b/target/debug/deps/libsignpost-1e4f64b0ea0e6988.rlib" "/files/mozilla/servo/b/target/debug/deps/libnet_traits-e53934f5aa667638.rlib" "/files/mozilla/servo/b/target/debug/deps/libwebsocket-bc74b41b937ace82.rlib" "/files/mozilla/servo/b/target/debug/deps/libuuid-3b9ce1f07977469a.rlib" "/files/mozilla/servo/b/target/debug/deps/libservo_config-868710c827d1cac5.rlib" "/files/mozilla/servo/b/target/debug/deps/libservo_url-7cc1fcdf6b658188.rlib" "/files/mozilla/servo/b/target/debug/deps/libservo_geometry-b0e6fa650b721abe.rlib" "/files/mozilla/servo/b/target/debug/deps/libgetopts-5df999ef913bf08b.rlib" "/files/mozilla/servo/b/target/debug/deps/libhyper_serde-e20a9d508de3a246.rlib" "/files/mozilla/servo/b/target/debug/deps/libhyper-2ba17e4ecfde2fff.rlib" "/files/mozilla/servo/b/target/debug/deps/libmime-a07933efeeec1ba7.rlib" "/files/mozilla/servo/b/target/debug/deps/liblanguage_tags-69c1ab0d09b59b1d.rlib" "/files/mozilla/servo/b/target/debug/deps/libsolicit-4aabafde27b296ca.rlib" "/files/mozilla/servo/b/target/debug/deps/libhpack-0d3ec62594868b95.rlib" "/files/mozilla/servo/b/target/debug/deps/libtypeable-e75322c8ff21a826.rlib" "/files/mozilla/servo/b/target/debug/deps/libtraitobject-fe0cff88b337a07d.rlib" "/files/mozilla/servo/b/target/debug/deps/libopenssl_verify-87b0b8a5c41b5c13.rlib" "/files/mozilla/servo/b/target/debug/deps/libcookie-17ec2720354c5830.rlib" "/files/mozilla/servo/b/target/debug/deps/libopenssl-d0239bceb4b171df.rlib" "/files/mozilla/servo/b/target/debug/deps/libopenssl_sys_extras-c1e879bbd965fc15.rlib" "/files/mozilla/servo/b/target/debug/deps/libopenssl_sys-042fd3c1f4c79649.rlib" "/files/mozilla/servo/b/target/debug/deps/liburl-69dd3c5b31f20196.rlib" "/files/mozilla/servo/b/target/debug/deps/libidna-6c12fbac46d1da27.rlib" "/files/mozilla/servo/b/target/debug/deps/libunicode_normalization-18b53bd46355e1fc.rlib" "/files/mozilla/servo/b/target/debug/deps/libunicode_bidi-a2e0f8afa8dba7e2.rlib" "/files/mozilla/servo/b/target/debug/deps/libmsg-16834b911237e422.rlib" "/files/mozilla/servo/b/target/debug/deps/libhtml5ever_atoms-1baff5a555f6787e.rlib" "/files/mozilla/servo/b/target/debug/deps/libstring_cache-e5224a204cf01c1e.rlib" "/files/mozilla/servo/b/target/debug/deps/libstring_cache_shared-a3e7a2971298ec41.rlib" "/files/mozilla/servo/b/target/debug/deps/libphf_shared-53dc14dc60a22f05.rlib" "/files/mozilla/servo/b/target/debug/deps/libunicase-ceb43341bcf99e15.rlib" "/files/mozilla/servo/b/target/debug/deps/libgfx_traits-d541d9b99f812162.rlib" "/files/mozilla/servo/b/target/debug/deps/librange-295e310b9195577d.rlib" "/files/mozilla/servo/b/target/debug/deps/libcanvas_traits-88a687a4f5c5882f.rlib" "/files/mozilla/servo/b/target/debug/deps/libwebrender_traits-9d84f5c85dec5aeb.rlib" "/files/mozilla/servo/b/target/debug/deps/liboffscreen_gl_context-0e1b86e365ae1894.rlib" "/files/mozilla/servo/b/target/debug/deps/libx11-e9d4115c095c5856.rlib" "/files/mozilla/servo/b/target/debug/deps/libgleam-8ed769a87854c571.rlib" "/files/mozilla/servo/b/target/debug/deps/libipc_channel-c63f2cd8ac6009c1.rlib" "/files/mozilla/servo/b/target/debug/deps/libbincode-d9a2cfd1007d0930.rlib" "/files/mozilla/servo/b/target/debug/deps/libeuclid-eafa6cf805f3092e.rlib" "/files/mozilla/servo/b/.servo/rust/2017-01-06/rustc-nightly-x86_64-unknown-linux-gnu/rustc/lib/rustlib/x86_64-unknown-linux-gnu/lib/libtest-c268df46a455da2e.rlib" "/files/mozilla/servo/b/.servo/rust/2017-01-06/rustc-nightly-x86_64-unknown-linux-gnu/rustc/lib/rustlib/x86_64-unknown-linux-gnu/lib/libterm-3b032f1a18504e83.rlib" "/files/mozilla/servo/b/.servo/rust/2017-01-06/rustc-nightly-x86_64-unknown-linux-gnu/rustc/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgetopts-9f0027fbffa38971.rlib" "/files/mozilla/servo/b/target/debug/deps/libcssparser-2701e375e0c0d1e4.rlib" "/files/mozilla/servo/b/target/debug/deps/libmatches-4da797c7d767d37a.rlib" "/files/mozilla/servo/b/target/debug/deps/libencoding-4a7f8e8048100da4.rlib" "/files/mozilla/servo/b/target/debug/deps/libencoding_index_tradchinese-5294236635e6e3a2.rlib" "/files/mozilla/servo/b/target/debug/deps/libencoding_index_simpchinese-40692a20d257a8b8.rlib" "/files/mozilla/servo/b/target/debug/deps/libencoding_index_japanese-003fef2ac0e48202.rlib" "/files/mozilla/servo/b/target/debug/deps/libencoding_index_korean-f553da378fcc5a92.rlib" "/files/mozilla/servo/b/target/debug/deps/libatomic_refcell-96f2f590f7bb427b.rlib" "/files/mozilla/servo/b/target/debug/deps/libapp_units-2f1ab06fac05beee.rlib" "/files/mozilla/servo/b/target/debug/deps/libserde-fadcd156e4e7fbbf.rlib" "/files/mozilla/servo/b/target/debug/deps/libheapsize-daa4a2dd8c23ea97.rlib" "/files/mozilla/servo/b/target/debug/deps/libencoding_index_singlebyte-07e706015af04a69.rlib" "/files/mozilla/servo/b/target/debug/deps/libblurmock-808ca095daf471f4.rlib" "/files/mozilla/servo/b/target/debug/deps/libfutf-42a4d73e8a2fcac9.rlib" "/files/mozilla/servo/b/target/debug/deps/libmac-25f1185ec77008ec.rlib" "/files/mozilla/servo/b/target/debug/deps/libdebug_unreachable-15577eef214d576d.rlib" "/files/mozilla/servo/b/target/debug/deps/libbacktrace_sys-3709b6cab508022c.rlib" "/files/mozilla/servo/b/target/debug/deps/libhttparse-996fc9116d9dcf83.rlib" "/files/mozilla/servo/b/target/debug/deps/libmio-81fc9ec840ad4248.rlib" "/files/mozilla/servo/b/target/debug/deps/libnet2-c30663e23539c2b0.rlib" "/files/mozilla/servo/b/target/debug/deps/libcfg_if-77c3f40a2736ac94.rlib" "/files/mozilla/servo/b/target/debug/deps/libmiow-6a749c7637c42ecc.rlib" "/files/mozilla/servo/b/target/debug/deps/libwinapi-3f4827e2e513c3d9.rlib" "/files/mozilla/servo/b/target/debug/deps/libnix-ff0ddd36ca816e44.rlib" "/files/mozilla/servo/b/target/debug/deps/libbitflags-a2e309ac4b5b98e2.rlib" "/files/mozilla/servo/b/target/debug/deps/libslab-bf9167e54ea6182f.rlib" "/files/mozilla/servo/b/target/debug/deps/libtime-83b34d2296f57844.rlib" "/files/mozilla/servo/b/target/debug/deps/libbytes-cadca398deca1f2c.rlib" "/files/mozilla/servo/b/target/debug/deps/liballoc_no_stdlib-6ef628235f6f19fb.rlib" "/files/mozilla/servo/b/target/debug/deps/libxdg-04554b3db1978c8d.rlib" "/files/mozilla/servo/b/target/debug/deps/libunreachable-5f1b8e6d5ca957aa.rlib" "/files/mozilla/servo/b/target/debug/deps/libvoid-1bc991dccafa33d3.rlib" "/files/mozilla/servo/b/target/debug/deps/libthread_id-29cf57da6bdc517a.rlib" "/files/mozilla/servo/b/target/debug/deps/libowning_ref-cac195f7ec2abf33.rlib" "/files/mozilla/servo/b/target/debug/deps/libglutin-5293924c108ffece.rlib" "/files/mozilla/servo/b/target/debug/deps/libwayland_window-76b9c6d466c9965d.rlib" "/files/mozilla/servo/b/target/debug/deps/libtempfile-6b2adab9cb0492e5.rlib" "/files/mozilla/servo/b/target/debug/deps/libwayland_kbd-ffe4eebfd240747c.rlib" "/files/mozilla/servo/b/target/debug/deps/libmemmap-6cf866b5120c6cd0.rlib" "/files/mozilla/servo/b/target/debug/deps/libosmesa_sys-ec5a9738717ca034.rlib" "/files/mozilla/servo/b/target/debug/deps/libimage-dacf166d5bac18b6.rlib" "/files/mozilla/servo/b/target/debug/deps/libscoped_threadpool-5fcccf18a82fddab.rlib" "/files/mozilla/servo/b/target/debug/deps/libgif-8c63bbd90a6ca285.rlib" "/files/mozilla/servo/b/target/debug/deps/libcolor_quant-92198e14504df971.rlib" "/files/mozilla/servo/b/target/debug/deps/liblzw-1ea3d44d9b1e4656.rlib" "/files/mozilla/servo/b/target/debug/deps/libjpeg_decoder-0e82fbe64bdb7073.rlib" "/files/mozilla/servo/b/target/debug/deps/librayon-9effd073b7bb231e.rlib" "/files/mozilla/servo/b/target/debug/deps/libnum_cpus-6aafd1243ce2bc30.rlib" "/files/mozilla/servo/b/target/debug/deps/libdeque-5759cf2da061d924.rlib" "/files/mozilla/servo/b/target/debug/deps/libpng-972d3112d6c0609d.rlib" "/files/mozilla/servo/b/target/debug/deps/libflate2-cbd36cd25ff8049c.rlib" "/files/mozilla/servo/b/target/debug/deps/libminiz_sys-91f1a57ff7ed73c5.rlib" "/files/mozilla/servo/b/target/debug/deps/libinflate-2bfd93a41ac0bcd2.rlib" "/files/mozilla/servo/b/target/debug/deps/libenum_primitive-787e523ca8566a76.rlib" "/files/mozilla/servo/b/target/debug/deps/libnum-324e13f9ba3b2c7d.rlib" "/files/mozilla/servo/b/target/debug/deps/libnum_rational-d0b5e68d571128ad.rlib" "/files/mozilla/servo/b/target/debug/deps/libnum_bigint-ab518bd16dd376c5.rlib" "/files/mozilla/servo/b/target/debug/deps/librand-26cfd8d095643d5f.rlib" "/files/mozilla/servo/b/target/debug/deps/librustc_serialize-03b62901d97343ea.rlib" "/files/mozilla/servo/b/target/debug/deps/libnum_iter-a08cc27ee32e82a2.rlib" "/files/mozilla/servo/b/target/debug/deps/libnum_integer-4c819e48d5fcce89.rlib" "/files/mozilla/servo/b/target/debug/deps/libnum_traits-ba977ae2944b0245.rlib" "/files/mozilla/servo/b/target/debug/deps/libbyteorder-1f7440bade571c5b.rlib" "/files/mozilla/servo/b/target/debug/deps/libwayland_client-6c3b9379a59035c0.rlib" "/files/mozilla/servo/b/target/debug/deps/libwayland_sys-608a1e94a779d497.rlib" "/files/mozilla/servo/b/target/debug/deps/liblazy_static-558fd24daf596ca5.rlib" "/files/mozilla/servo/b/target/debug/deps/libdlib-56051235fe0c7bbb.rlib" "/files/mozilla/servo/b/target/debug/deps/liblibloading-98b048309438d220.rlib" "/files/mozilla/servo/b/target/debug/deps/libcrossbeam-2940ee62eaca4f2c.rlib" "/files/mozilla/servo/b/target/debug/deps/libbitflags-725a4e5043ace390.rlib" "/files/mozilla/servo/b/target/debug/deps/libx11_dl-cd8a87479396bae4.rlib" "/files/mozilla/servo/b/target/debug/deps/libshared_library-7046f0f739c6841c.rlib" "/files/mozilla/servo/b/target/debug/deps/liblibc-73c6422e7b19c2f3.rlib" "/files/mozilla/servo/b/target/debug/deps/libservo_remutex-d63e0f0163b8726d.rlib" "/files/mozilla/servo/b/target/debug/deps/liblog-544a4b1221d64c1f.rlib" "/files/mozilla/servo/b/target/debug/deps/liblazy_static-13daae1d9a07c252.rlib" "/files/mozilla/servo/b/.servo/rust/2017-01-06/rustc-nightly-x86_64-unknown-linux-gnu/rustc/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-93390f7535a2b2f7.rlib" "/files/mozilla/servo/b/.servo/rust/2017-01-06/rustc-nightly-x86_64-unknown-linux-gnu/rustc/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-277781e5e83f4ddf.rlib" "/files/mozilla/servo/b/.servo/rust/2017-01-06/rustc-nightly-x86_64-unknown-linux-gnu/rustc/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-9fb0680200b1f1d7.rlib" "/files/mozilla/servo/b/.servo/rust/2017-01-06/rustc-nightly-x86_64-unknown-linux-gnu/rustc/lib/rustlib/x86_64-unknown-linux-gnu/lib/librand-8fe8e03da90d4fd4.rlib" "/files/mozilla/servo/b/.servo/rust/2017-01-06/rustc-nightly-x86_64-unknown-linux-gnu/rustc/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcollections-91e6e43d741825a3.rlib" "/files/mozilla/servo/b/.servo/rust/2017-01-06/rustc-nightly-x86_64-unknown-linux-gnu/rustc/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-91c6f0edecc68d05.rlib" "/files/mozilla/servo/b/.servo/rust/2017-01-06/rustc-nightly-x86_64-unknown-linux-gnu/rustc/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc_jemalloc-3e3384d4e8c6562d.rlib" "/files/mozilla/servo/b/.servo/rust/2017-01-06/rustc-nightly-x86_64-unknown-linux-gnu/rustc/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-552ce29795ce9c9d.rlib" "/files/mozilla/servo/b/.servo/rust/2017-01-06/rustc-nightly-x86_64-unknown-linux-gnu/rustc/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd_unicode-e19b6c0e5bf50406.rlib" "/files/mozilla/servo/b/.servo/rust/2017-01-06/rustc-nightly-x86_64-unknown-linux-gnu/rustc/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-c1ab5423a7223378.rlib" "/files/mozilla/servo/b/.servo/rust/2017-01-06/rustc-nightly-x86_64-unknown-linux-gnu/rustc/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-5d4fca8590bb0079.rlib" "-l" "dbus-1" "-l" "skia" "-l" "GL" "-l" "stdc++" "-l" "freetype" "-l" "bz2" "-l" "fontconfig" "-l" "expat" "-l" "X11" "-l" "azure" "-l" "stdc++" "-l" "bz2" "-l" "GL" "-l" "stdc++" "-l" "stdc++" "-l" "z" "-l" "harfbuzz" "-l" "stdc++" "-l" "fontconfig" "-l" "freetype" "-l" "expat" "-l" "ssl" "-l" "crypto" "-l" "X11" "-l" "GL" "-l" "dl" "-l" "dl" "-l" "util" "-l" "dl" "-l" "rt" "-l" "pthread" "-l" "gcc_s" "-l" "pthread" "-l" "c" "-l" "m" "-l" "rt" "-l" "util" "-fuse-ld=gold"
  = note: /files/mozilla/servo/b/target/debug/deps/libscript-2203cc0d1eeee2a4.rlib(script-2203cc0d1eeee2a4.5.o):script.cgu-5.rs:function core::ops::FnMut::call_mut::hde33d31122b8afb5: error: undefined reference to '_$LT$script..dom..bindings..js..Root$LT$T$GT$$GT$::downcast::h91b0ac4007c4c9f0'
/files/mozilla/servo/b/.cargo/registry/src/github.com-1ecc6299db9ec823/ipc-channel-0.5.1/src/platform/mod.rs:12: warning: the use of `mktemp' is dangerous, better use `mkstemp' or `mkdtemp'
collect2: error: ld returned 1 exit status

error: aborting due to previous error

error: Could not compile `servo`.

**Comment by bholley** [comment]
CC @Manishearth @jdm @metajack

**Comment by jdm** [comment]
Closing in favour of the https://github.com/rust-lang/rust/issues/38938.
