### PR TITLE
style: sync changes from mozilla-central.

### PR DESCRIPTION
**Pull request by emilio**
See each individual commit for details..

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/21109)

### CODE REVIEW

**Comment by CYBAI** [comment]
All environments (homu, Travis and Appveyor) have the following error:

```rust
error[E0432]: unresolved import `style::media_queries::Expression`
 --> tests\unit\script\htmlimageelement.rs:9:5
  |
9 | use style::media_queries::Expression;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `Expression` in `media_queries`

error[E0560]: struct `style::media_queries::MediaQuery` has no field named `expressions`
  --> tests\unit\script\htmlimageelement.rs:47:9
   |
47 |         expressions: vec![expr]
   |         ^^^^^^^^^^^ `style::media_queries::MediaQuery` does not have this field
   |
   = note: available fields are: `qualifier`, `media_type`, `condition`

error: aborting due to 2 previous errors
```

**Comment by emilio** [comment]
Ugh, thanks @CYBAI.

@nox / @SimonSapin / @jdm, mind stamping the last commit (https://github.com/servo/servo/pull/21109/commits/36495d677f6e5e928c74f8eb372caaae7a303047)?

As mentioned in the commit message code for this exists already in `style` under `components/style/values/specified/source_size_list.rs`.

**Comment by SimonSapin** [comment]
I notice that not even one line was changed to use the other implementation of this. Was this dead code?

**Comment by emilio** [comment]
Yes, it's unused.

**Comment by emilio** [comment]
And it was introduced in c31b0e4bd2777aaaa822ffa9e7df6e80c793f2db (unused as well).

**Comment by SimonSapin** [comment]
Removing dead code is an automatic r+ in my book :)

@bors-servo r+

**Comment by CYBAI** [comment]
Travis failed with

```rust
failures:
---- http_loader::test_redirected_request_to_devtools stdout ----
thread 'http_loader::test_redirected_request_to_devtools' panicked at 'assertion failed: `(left == right)`
  left: `Get`,
 right: `Post`', components/net/tests/http_loader.rs:346:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:221
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:511
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:426
   6: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:413
   7: main::http_loader::test_redirected_request_to_devtools
             at components/net/tests/http_loader.rs:346
   8: main::__test::TESTS::{{closure}}
             at components/net/tests/http_loader.rs:314
   9: core::ops::function::FnOnce::call_once
             at /checkout/src/libcore/ops/function.rs:223
  10: <F as alloc::boxed::FnBox<A>>::call_box
             at libtest/lib.rs:1451
             at /checkout/src/libcore/ops/function.rs:223
             at /checkout/src/liballoc/boxed.rs:640
  11: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
failures:
    http_loader::test_redirected_request_to_devtools
test result: FAILED. 420 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
```
