### PR TITLE
Remove usage of opts::get() from style.

### PR DESCRIPTION
**Pull request by kitlith**
Use `AtomicBool`s to create a global storage for a couple of settings used by an implementation of `Default`, suggested in https://github.com/servo/servo/issues/22854#issuecomment-540955207.

I do have one main question: I'm currently setting these statics in `Servo::new()`, would there be a better place to put this? Same goes with making these `pub`, is there a better way to go about this?

---

- [X] `./mach build -d` does not report any errors
  - Seems to be failing in script for unknown/unrelated reasons, experiencing SIGKILL on two different machines. (May be an issue with the latest commit?) Still works fine on CI though.
- [X] `./mach test-tidy` does not report any errors
- [X] These changes help with #22854

These changes do not require tests because these are cleanup changes.

### CODE REVIEW

**Comment by kitlith** [comment]
sigh. well the build failure is definitely from master, because that's what I was trying to build on the second machine. test-tidy should be fixed now.

File: components/servo/lib.rs [hunk 1]
```diff
@@ -310,6 +310,13 @@ where
         // Global configuration options, parsed from the command line.
         let opts = opts::get();
 
+        use std::sync::atomic::Ordering;
+
+        style::context::DEFAULT_DISABLE_STYLE_SHARING_CACHE
+            .store(opts.disable_share_style_cache, Ordering::SeqCst);
```
Comment (emilio) [inline components/servo/lib.rs]: Just `Relaxed` is fine.

File: components/style/context.rs [hunk 2]
```diff
@@ -103,14 +103,28 @@ fn get_env_usize(name: &str) -> Option<usize> {
     })
 }
 
+/// A global variable holding the state of
+/// `StyleSystemOptions::default().disable_style_sharing_cache`.
+/// This is motivated by [issue #22854](https://github.com/servo/servo/issues/22854).
```
Comment (emilio) [inline components/style/context.rs]: I don't think this line of the comment is useful, it only makes sense in the context of this PR.

File: components/style/context.rs [hunk 3]
```diff
@@ -103,14 +103,28 @@ fn get_env_usize(name: &str) -> Option<usize> {
...
 impl Default for StyleSystemOptions {
     #[cfg(feature = "servo")]
     fn default() -> Self {
-        use servo_config::opts;
+        use std::sync::atomic::Ordering;
 
         StyleSystemOptions {
-            disable_style_sharing_cache: opts::get().disable_share_style_cache,
-            dump_style_statistics: opts::get().style_sharing_stats,
+            disable_style_sharing_cache: DEFAULT_DISABLE_STYLE_SHARING_CACHE.load(Ordering::SeqCst),
```
Comment (emilio) [inline components/style/context.rs]: Same, just relaxed is fine.

**Review by emilio — COMMENTED** [review]
This seems ok. @jdm is this the pattern that other code has been following? I guess it does accomplish the "changing opts rebuilds less" bits (assuming we remove the other usage in the crate and the dependency), but the pattern seems somewhat weird.

**Comment by jdm** [comment]
This is our first time trying this pattern, since we skipped other uses of opts::get inside static functions. I'm in favour.

File: components/style/context.rs (hunk 2 above)
Comment (kitlith) [reply components/style/context.rs]: I thought I'd try to leave the issue link for motivation especially because this is an odder pattern than usual, to try and preempt "why not just use `opts::get()`" for people not familiar with the issue.

Comment (emilio) [reply components/style/context.rs]: I still think it's not particularly useful. I assume we'd get rid of `opts` as a dependency of `style` after changing the other similar uses. Once that's done, if somebody wants to use `opts::get()` again they need to re-introduce it as a dependency, which makes the consequences of it much more obvious.

Not going to block this patch on removing this comment, but I don't quite see the point of it... Maybe just `See #22854` is a good compromise?

Either way this looks ok, mind squashing? Thanks!

Comment (kitlith) [reply components/style/context.rs]: K, I'll do that and squash once I'm at a computer.

**Comment by kitlith** [comment]
I just noticed that there's only a single `opts::get()` left in the style component:

https://github.com/servo/servo/blob/882dcc8408159bed5633337d11e83b6839f97e34/components/style/traversal.rs#L48-L54

Would you like me to apply the same pattern here and remove opts from the dependency tree of this crate?

**Comment by jdm** [comment]
Yes please!

**Comment by emilio** [comment]
That'd indeed be ideal. Do you plan to do this as part of this PR or a new one? (Just to know if I should submit the current PR as is :))

**Comment by kitlith** [comment]
I can do that in this PR, but it might take a bit so you can merge if impatient. (I don't mind doing it in a seperate one either, gets me another PR towards octoberfest lol, but i'd prefer not to PR spam)

**Review by emilio — APPROVED** [review]
Two PRs doing two different things is not spam, in my book ;)

Anyhow, let's submit this. If you get to push your other changes before it lands then it will just not get merged and we'll review those too. Otherwise new PR is fine :)

**Comment by kitlith** [comment]
Uh? I don't think I touched anything related to the tests that changed...

Anyway, I'll get rid of the other usage I mentioned earlier now.

**Comment by kitlith** [comment]
So: we can't remove the dep on servo_config yet because style still relies on pref in a few places. This feels like something that is not as easilly replaced...

**Comment by emilio** [comment]
> So: we can't remove the dep on servo_config yet because style still relies on pref in a few places. This feels like something that is not as easilly replaced...

Ah, that is a good point... :/

So there's no realistic path to get rid of the dependency for now... Is there any point in removing `opts::get()` usage then @jdm?

**Comment by jdm** [comment]
There is! I want to split prefs and options into separate crates in the future, so this work is still useful.

**Comment by jdm** [comment]
@bors-servo r=emilio
And to clear up the earlier mystery, the test failure was caused by #23290.

**Comment by jdm** [comment]
```
error[E0308]: mismatched types
  --> components/style/traversal.rs:57:40
   |
57 | fn is_servo_nonincremental_layout() -> bool {
   |    ------------------------------      ^^^^ expected bool, found ()
   |    |
   |    implicitly returns `()` as its body has no tail or `return` expression
...
60 |     IS_SERVO_NONINCREMENTAL_LAYOUT.load(Ordering::Relaxed);
   |                                                           - help: consider removing this semicolon
   |
   = note: expected type `bool`
              found type `()`

error: aborting due to previous error
```

**Comment by kitlith** [comment]
*facepalm*
