### ISSUE TITLE
MotionMark benchmark doesn't run

### ISSUE THREAD

**Issue by jgraham** [servo/servo#13373]
It would be nice to see how Servo does in [MotionMark](https://webkit.org/blog/6943/motionmark-a-new-graphics-benchmark/). However this seems to not work, probably for a variety of reasons.

The first error I see is:

    ERROR:script::dom::bindings::error: Error at http://browserbench.org/MotionMark/resources/runner/animometer.js:443:21 window.matchMedia is not a function

**Comment by jdm** [comment]
Filed #13376 for matchMedia. Turning this into a metabug.

**Comment by Manishearth** [comment]
MotionMark has JS errors in Firefox and Chrome. It also seems to have JS errors in Safari, which doesn't really make sense.

**Comment by Manishearth** [comment]
Oh, this is because the windows weren't active. Chrome/Safari work. TEsting firefox

**Comment by Manishearth** [comment]
Okay, works in firefox too. But firefox has some differences in the animations.

**Comment by metajack** [comment]
With latest WR update (#13474 which hasn't yet landed) the test seems to run as expected, and all objects appear to be there at least until the error caused by #13451.

**Comment by metajack** [comment]
Marking this easy. The task here is to run Servo on this benchmark and file bugs for any errors you find that prevent it from running.

**Comment by lumiscosity** [comment]
Stops after the 4 circles with rectangles with:
```
[2025-07-29T09:57:04Z ERROR script::dom::bindings::error] Error at https://browserbench.org/MotionMark/resources/extensions.js:112:13 prefix is undefined
```
Tested on Arch Linux x86_64, Servo built against commit 239bdd7c1a12f7bdb5da2c20f4f5226c4a9294e9, profiling build, experimental web features on with no other prefs.

**Comment by jdm** [comment]
```js
        // Get the HTML element's CSSStyleDeclaration
        var styles = window.getComputedStyle(document.documentElement, '');

        // Convert the styles list to an array
        var stylesArray = Array.prototype.slice.call(styles);

        // Concatenate all the styles in one big string
        var stylesString = stylesArray.join('');

        // Search the styles string for a known prefix type, settle on Opera if none is found.
        var prefixes = stylesString.match(/-(moz|webkit|ms)-/) || (styles.OLink === '' && ['', 'o']);

        // prefixes has two elements; e.g. for webkit it has ['-webkit-', 'webkit'];
        var prefix = prefixes[1];

         /*...*/

         prefix[0].toUpperCase() + prefix.substr(1)
```

We don't include any vendor-prefixed CSS properties in our CSSStyleDeclaration, apparently, and this confounds the webpage.

**Comment by mrobinson** [comment]
After #42181, this seems to fail with:

```
[2026-01-27T10:43:21Z ERROR script::dom::bindings::error] Error at https://browserbench.org/MotionMark/tests/master/resources/svg-particles.js:51:44 this.stage.element.createSVGTransform is not a function
```
