### ISSUE TITLE
Unable to create dev builds on Windows

### ISSUE THREAD

**Issue by ferjm** [servo/servo#21604]
I can perfectly build Servo in release mode. But when I try a dev build I am get a bunch of linker errors like:
```
          libservo-8358b3da2893e936.rlib(servo-8358b3da2893e936.1ks3n3t8e6o7dcp0.rcgu.o) : error LNK2019: unresolved external symbol _ZN76_$LT$std..sync..mpsc..Receiver$LT$T$GT$$u20$as$u20$core..ops..drop..Drop$GT$4drop17h1b96090abb62b20fE referenced in function _ZN4core3ptr13drop_in_place17h54e0ecf729bc553cE
          liblayout_thread-80b590f910b4355c.rlib(layout_thread-80b590f910b4355c.3jyjsv4oyqmulv39.rcgu.o) : error LNK2001: unresolved external symbol _ZN76_$LT$std..sync..mpsc..Receiver$LT$T$GT$$u20$as$u20$core..ops..drop..Drop$GT$4drop17h1b96090abb62b20fE
          libservo-8358b3da2893e936.rlib(servo-8358b3da2893e936.1ks3n3t8e6o7dcp0.rcgu.o) : error LNK2019: unresolved external symbol _ZN71_$LT$alloc..vec..IntoIter$LT$T$GT$$u20$as$u20$core..ops..drop..Drop$GT$4drop17h032672dd044efb52E referenced in function _ZN4core3ptr13drop_in_place17h731bb0a2215d8f2aE
          libservo-8358b3da2893e936.rlib(servo-8358b3da2893e936.1ks3n3t8e6o7dcp0.rcgu.o) : error LNK2019: unresolved external symbol _ZN67_$LT$alloc..sync..Arc$LT$T$GT$$u20$as$u20$core..ops..drop..Drop$GT$4drop17h388aaafa9d51e000E referenced in function _ZN4core3ptr13drop_in_place17h8f085add7a63991eE
          liblayout_thread-80b590f910b4355c.rlib(layout_thread-80b590f910b4355c.3jyjsv4oyqmulv39.rcgu.o) : error LNK2001: unresolved external symbol _ZN67_$LT$alloc..sync..Arc$LT$T$GT$$u20$as$u20$core..ops..drop..Drop$GT$4drop17h388aaafa9d51e000E
          libservo-8358b3da2893e936.rlib(servo-8358b3da2893e936.1ks3n3t8e6o7dcp0.rcgu.o) : error LNK2019: unresolved external symbol _ZN67_$LT$alloc..sync..Arc$LT$T$GT$$u20$as$u20$core..ops..drop..Drop$GT$4drop17hb58bb9fd7c9b1037E referenced in function _ZN4core3ptr13drop_in_place17h90db8f2efd5aa036E
          liblayout_thread-80b590f910b4355c.rlib(layout_thread-80b590f910b4355c.3jyjsv4oyqmulv39.rcgu.o) : error LNK2001: unresolved external symbol _ZN67_$LT$alloc..sync..Arc$LT$T$GT$$u20$as$u20$core..ops..drop..Drop$GT$4drop17hb58bb9fd7c9b1037E
          libservo-8358b3da2893e936.rlib(servo-8358b3da2893e936.1ks3n3t8e6o7dcp0.rcgu.o) : error LNK2019: unresolved external symbol _ZN67_$LT$alloc..sync..Arc$LT$T$GT$$u20$as$u20$core..ops..drop..Drop$GT$4drop17hbdd6aa9d88904bf3E referenced in function _ZN4core3ptr13drop_in_place17hb50c2e40b98a92f0E
          liblayout_thread-80b590f910b4355c.rlib(layout_thread-80b590f910b4355c.3jyjsv4oyqmulv39.rcgu.o) : error LNK2001: unresolved external symbol _ZN67_$LT$alloc..sync..Arc$LT$T$GT$$u20$as$u20$core..ops..drop..Drop$GT$4drop17hbdd6aa9d88904bf3E
          libservo-8358b3da2893e936.rlib(servo-8358b3da2893e936.1ks3n3t8e6o7dcp0.rcgu.o) : error LNK2019: unresolved external symbol _ZN67_$LT$alloc..sync..Arc$LT$T$GT$$u20$as$u20$core..ops..drop..Drop$GT$4drop17hd7adf32ab85f4355E referenced in function _ZN4core3ptr13drop_in_place17hbe24a9195f9c05b7E
liblayout_thread-80b590f910b4355c.rlib(layout_thread-80b590f910b4355c.3jyjsv4oyqmulv39.rcgu.o) : error LNK2001: unresolved external symbol _ZN67_$LT$alloc..sync..Arc$LT$T$GT$$u20$as$u20$core..ops..drop..Drop$GT$4drop17hd7adf32ab85f4355E
[...]
C:\Users\harpo\servo\target\debug\deps\simpleservo.dll : fatal error LNK1120: 619 unresolved externals
```

Full log [here](https://gist.github.com/ferjm/ce1cc6ecf492bf63bc8b763023de2dfc)

**Comment by asajeffrey** [comment]
Hmm, this may be caused by using MSVC 15.8. AFAICT from https://bugzilla.mozilla.org/show_bug.cgi?id=1484190, mozjs 63 is the first one which builds using MSVC 15.8, mozjs 60 (which is what servo uses) requires MSVC 15.6.

**Comment by ferjm** [comment]
I am indeed using MSVC 15.8.1. I'll try with 15.6. Thanks for the pointer!

**Comment by ferjm** [comment]
I am afraid that I am getting the same errors with VS 15.6 (14.13 toolchain).

Log [here](https://gist.github.com/ferjm/31b867d68e0fb5515161a3bdfa441c3b)

**Comment by asajeffrey** [comment]
Well this is odd... https://gist.github.com/ferjm/31b867d68e0fb5515161a3bdfa441c3b#file-gistfile1-txt-L110
```
note: C:\Users\harpo\servo\target\debug\deps\libscript-053cee47d03ec5aa.rlib : warning LNK4003: invalid library format; library ignored
```
is this from a fresh build? (The beginning of the log is truncated so I can't tell.)

**Comment by asajeffrey** [comment]
Thanks! That will be a bit log -vv is very chatty!

**Comment by ferjm** [comment]
I double checked that the dev build still fails with VS 15.6 after a `mach clean`.

I got a humongous [log](https://gist.github.com/ferjm/2c3a79567db5087ee288260fbd0dabc3#file-windows_build_veeeeeeery_verbose-log) with -vv.

**Comment by learning** [comment]
The same errors with `v15.9.3`

**Comment by Utkarsh1308** [comment]
I am getting this same error with 592 unresolved externals. Can anyone help?

**Comment by jdm** [comment]
Nobody has figured out why this happens yet, unfortunately.

**Comment by isaalia** [comment]
Root-caused this today while building a downstream fork on Windows (rustc/rust-toolchain 1.97.1, LLVM 22.1.6). Two genuinely separate bugs were compounding, and neither is what the thread here has been chasing:

**1. `libscript`'s debug `.rlib` corrupts once it crosses ~4GiB**

Ours came in at 4.39GB (`no-default-features` minus `multiprocess`, but this will trip on any config whose `script` crate debug archive gets that large). The link failure is:

```
lld-link: error: could not get child name for archive .../libscript-....rlib while loading symbol <sym>: truncated or malformed archive (string table at long name offset 0 not terminated)
```

This is exactly `llvm/llvm-project#160112` ("`llvm-lib` writes broken `.lib` files when output is > 4 GiB", fixed by #160606, merged 2025-09-28): the archive writer switches `Kind` to `K_GNU64` mid-write once 64-bit symbol offsets are needed, but earlier decisions were already made against the old `Kind`, corrupting the string table. Whether a given rustc's bundled LLVM has the backport is luck of the point-release; ours didn't.

Confirmed by reproducing it twice, including once against a freshly-regenerated (non-stale) archive, ruling out disk-level corruption.

**Workaround** (no LLVM patch needed): shrink `script`'s debug info so the archive stays under the trigger size, via a scoped Cargo profile override:

```toml
[profile.dev.package.script]
debug = "line-tables-only"
```

Keeps real line-number debugging (breakpoints, backtraces); drops the type/variable debug info that's what's ballooning the archive. This alone got a debug build to link for the first time in our checkout.

**2. Once it links, the debug binary panics on window creation — this is likely why past debug attempts here looked like they "just don't work" for other reasons**

`RUST_BACKTRACE=full` gives a full, non-silent panic (`surfman::egl::missing_fn_panic`, deep in `surfman::angle::device::Device::new` → `lookup_egl_extension` → `GetProcAddress` on a function the loaded `libEGL.dll` doesn't export). Root cause: neither `servoshell`'s own `build.rs` nor the `mozangle` crate's `build.rs` ever copies the ANGLE-built `libEGL.dll`/`libGLESv2.dll` out of `mozangle`'s own `OUT_DIR` to sit next to the final executable — for *any* profile. Windows then loads some other (mismatched, or absent) `libEGL.dll` off `PATH` at runtime, and `surfman` panics rather than erroring cleanly.

We had this masked because an old *release* build in our tree happened to have those DLLs sitting next to the exe from a one-off manual copy done ages ago — so release "worked" (by accident) while debug never got the same treatment, which reads exactly like "release works, debug doesn't" without the real cause (a missing runtime dependency) ever showing up.

**Fix**, in our `servoshell`'s `build.rs`, Windows-only, best-effort (skips silently if `mozangle`'s build script hasn't produced output yet):

```rust
if let Ok(entries) = std::fs::read_dir(build_script_output_root) {
    for entry in entries.flatten() {
        if !entry.file_name().to_string_lossy().starts_with("mozangle-") { continue; }
        let angle_out = entry.path().join("out");
        for dll in ["libEGL.dll", "libGLESv2.dll"] {
            let src = angle_out.join(dll);
            if src.exists() {
                let _ = std::fs::copy(&src, target_profile_dir.join(dll));
            }
        }
    }
}
```

(`build_script_output_root` = `OUT_DIR`'s grandparent, i.e. `target/<profile>/build`; `target_profile_dir` = its parent, `target/<profile>`.)

With both fixes in place, a debug build links and launches with a real window on this machine (NVIDIA RTX 5080, real D3D11 driver — not a headless/software-rendering environment).

Happy to open a proper PR against `servoshell`'s `build.rs` for (2) if that's useful upstream rather than just downstream — let me know. (1) is arguably worth a one-line note in the build docs pointing at the LLVM issue, since it'll bite anyone whose `script` crate debug build grows past 4GiB regardless of platform specifics.

**Comment by jdm** [comment]
Ah, did you build with `cargo build` intead of `mach build`? At minimum, we should document the post-build tasks that are currently handled by mach for anybody that builds servoshell with cargo directly.
