### ISSUE TITLE
Fails to build on Gentoo with Clang and Glibc 2.43 due to glslopt

### ISSUE THREAD

**Issue by theoparis** [servo/servo#42695]
**Describe the bug:**

See https://github.com/jamienicol/glslopt-rs/issues/12

```
  cargo:warning=In file included from glsl-optimizer/include/c11/threads.h:66,
  cargo:warning=                 from glsl-optimizer/src/mesa/main/mtypes.h:39,
  cargo:warning=                 from src/compiler/glsl/glcpp/glcpp-parse.y:32:
  cargo:warning=glsl-optimizer/include/c11/threads_posix.h:69:25: error: conflicting types for 'once_flag'; have 'pthread_once_t' {aka 'int'}
  cargo:warning=   69 | typedef pthread_once_t  once_flag;
  cargo:warning=      |                         ^~~~~~~~~
  cargo:warning=In file included from /usr/include/stdlib.h:1191,
  cargo:warning=                 from src/compiler/glsl/glcpp/glcpp-parse.y:26:
  cargo:warning=/usr/include/bits/types/once_flag.h:24:21: note: previous declaration of 'once_flag' with type 'once_flag'
  cargo:warning=   24 | typedef __once_flag once_flag;
  cargo:warning=      |                     ^~~~~~~~~
  cargo:warning=glsl-optimizer/include/c11/threads_posix.h:94:1: error: conflicting types for 'call_once'; have 'void(int *, void (*)(void))'
  cargo:warning=   94 | call_once(once_flag *flag, void (*func)(void))
  cargo:warning=      | ^~~~~~~~~
  cargo:warning=/usr/include/stdlib.h:1195:13: note: previous declaration of 'call_once' with type 'void(once_flag *, void (*)(void))'
  cargo:warning= 1195 | extern void call_once (once_flag *__flag, void (*__func)(void));
  cargo:warning=      |             ^~~~~~~~~
  cargo:warning=In file included from glsl-optimizer/include/c11/threads.h:66,
  cargo:warning=                 from glsl-optimizer/src/mesa/main/mtypes.h:39,
  cargo:warning=                 from glsl-optimizer/src/compiler/glsl/glcpp/pp_standalone_scaffolding.h:34,
  cargo:warning=                 from glsl-optimizer/src/compiler/glsl/glcpp/pp_standalone_scaffolding.c:30:
  cargo:warning=glsl-optimizer/include/c11/threads_posix.h:69:25: error: conflicting types for 'once_flag'; have 'pthread_once_t' {aka 'int'}
  cargo:warning=   69 | typedef pthread_once_t  once_flag;
  cargo:warning=      |                         ^~~~~~~~~
  cargo:warning=In file included from /usr/include/stdlib.h:1191,
  cargo:warning=                 from glsl-optimizer/include/c11/threads_posix.h:29:
  cargo:warning=/usr/include/bits/types/once_flag.h:24:21: note: previous declaration of 'once_flag' with type 'once_flag'
  cargo:warning=   24 | typedef __once_flag once_flag;
  cargo:warning=      |                     ^~~~~~~~~
  cargo:warning=glsl-optimizer/include/c11/threads_posix.h:94:1: error: conflicting types for 'call_once'; have 'void(int *, void (*)(void))'
  cargo:warning=   94 | call_once(once_flag *flag, void (*func)(void))
  cargo:warning=      | ^~~~~~~~~
  cargo:warning=/usr/include/stdlib.h:1195:13: note: previous declaration of 'call_once' with type 'void(once_flag *, void (*)(void))'
  cargo:warning= 1195 | extern void call_once (once_flag *__flag, void (*__func)(void));
  cargo:warning=      |             ^~~~~~~~~
  cargo:warning=In file included from glsl-optimizer/include/c11/threads.h:66,
  cargo:warning=                 from glsl-optimizer/src/mesa/main/mtypes.h:39,
  cargo:warning=                 from glsl-optimizer/src/compiler/glsl/glcpp/pp.c:28:
  cargo:warning=glsl-optimizer/include/c11/threads_posix.h:69:25: error: conflicting types for 'once_flag'; have 'pthread_once_t' {aka 'int'}
  cargo:warning=   69 | typedef pthread_once_t  once_flag;
  cargo:warning=      |                         ^~~~~~~~~
  cargo:warning=In file included from /usr/include/stdlib.h:1191,
  cargo:warning=                 from glsl-optimizer/src/util/hash_table.h:31,
  cargo:warning=                 from glsl-optimizer/src/compiler/glsl/glcpp/glcpp.h:34,
  cargo:warning=                 from glsl-optimizer/src/compiler/glsl/glcpp/pp.c:27:
  cargo:warning=/usr/include/bits/types/once_flag.h:24:21: note: previous declaration of 'once_flag' with type 'once_flag'
  cargo:warning=   24 | typedef __once_flag once_flag;
  cargo:warning=      |                     ^~~~~~~~~
  cargo:warning=glsl-optimizer/include/c11/threads_posix.h:94:1: error: conflicting types for 'call_once'; have 'void(int *, void (*)(void))'
  cargo:warning=   94 | call_once(once_flag *flag, void (*func)(void))
  cargo:warning=      | ^~~~~~~~~
  cargo:warning=/usr/include/stdlib.h:1195:13: note: previous declaration of 'call_once' with type 'void(once_flag *, void (*)(void))'
  cargo:warning= 1195 | extern void call_once (once_flag *__flag, void (*__func)(void));
  cargo:warning=      |             ^~~~~~~~~
  exit status: 0
  exit status: 0
  exit status: 0
  exit status: 1
```

**To Reproduce:**

Use glibc 2.43 on a distro such as Arch Linux or Gentoo.

**Comment by jerensl** [comment]
I also have the same issues with Arch Linux as of today

```
warning: glslopt@0.1.12: 2 errors generated.
warning: glslopt@0.1.12: ToolExecError: command did not execute successfully (status code exit status: 1): LC_ALL="C" "clang" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "--target=x86_64-unknown-linux-gnu" "-I" "glsl-optimizer/include" "-I" "glsl-optimizer/src/mesa" "-I" "glsl-optimizer/src/mapi" "-I" "glsl-optimizer/src/compiler" "-I" "glsl-optimizer/src/compiler/glsl" "-I" "glsl-optimizer/src/gallium/auxiliary" "-I" "glsl-optimizer/src/gallium/include" "-I" "glsl-optimizer/src" "-I" "glsl-optimizer/src/util" "-w" "-D__STDC_FORMAT_MACROS" "-D_GNU_SOURCE" "-DHAVE_ENDIAN_H" "-DHAVE_PTHREAD" "-DHAVE_TIMESPEC_GET" "-DMOZILLA_CONFIG_H" "-DMOZ_INCLUDE_MOZALLOC_H" "-Dmozilla_throw_gcc_h" "-o" "/home/jerensl/Projects/servo/target/debug/build/glslopt-e1646ae70e9fc5fd/out/ecc5ce2ee3e1d37b-pp.o" "-c" "glsl-optimizer/src/compiler/glsl/glcpp/pp.c"
error: failed to run custom build command for `glslopt v0.1.12`

```

**Comment by sagudev** [comment]
As a workaround I suggest using devcontainer, real fix needs to be done in upstream.

**Comment by kkoyung** [comment]
I just checked the Arch Linux repository to see how they patch this issue in their Firefox build, which also depends on glslopt-rs. Based on [their patch](https://gitlab.archlinux.org/archlinux/packaging/packages/firefox/-/blob/d82490f5db9d55f3e5e61b640c6618ab209aa06b/0003-Patch-glsl-optimizer-to-build-with-glibc-2.43.patch), I came up with the following temporary workaround.

```bash
# Clone `glslopt-rs` repository, and get submodule
git clone https://github.com/jamienicol/glslopt-rs
cd glslopt-rs
git submodule update --init
```

Then, apply the following changes to the submodule in `glsl-optimizer/`

```diff
diff --git a/include/c11/threads_posix.h b/include/c11/threads_posix.h
index 45cb6075e6e..19bb03fb2e5 100644
--- a/include/c11/threads_posix.h
+++ b/include/c11/threads_posix.h
@@ -47,11 +47,16 @@ Configuration macro:
 #define EMULATED_THREADS_USE_NATIVE_TIMEDLOCK
 #endif

+#ifndef ONCE_FLAG_INIT
+#define ONCE_FLAG_USE_PTHREAD_ONCE
+#endif

 #include <pthread.h>

 /*---------------------------- macros ----------------------------*/
+#ifdef ONCE_FLAG_USE_PTHREAD_ONCE
 #define ONCE_FLAG_INIT PTHREAD_ONCE_INIT
+#endif
 #ifdef INIT_ONCE_STATIC_INIT
 #define TSS_DTOR_ITERATIONS PTHREAD_DESTRUCTOR_ITERATIONS
 #else
@@ -66,7 +71,9 @@ typedef pthread_cond_t  cnd_t;
 typedef pthread_t       thrd_t;
 typedef pthread_key_t   tss_t;
 typedef pthread_mutex_t mtx_t;
+#ifdef ONCE_FLAG_USE_PTHREAD_ONCE
 typedef pthread_once_t  once_flag;
+#endif


 /*
@@ -90,11 +97,13 @@ impl_thrd_routine(void *p)

 /*--------------- 7.25.2 Initialization functions ---------------*/
 // 7.25.2.1
+#ifdef ONCE_FLAG_USE_PTHREAD_ONCE
 static inline void
 call_once(once_flag *flag, void (*func)(void))
 {
     pthread_once(flag, func);
 }
+#endif


 /*------------- 7.25.3 Condition variable functions -------------*/
```

Finally, add the following line under `[patch.crates-io]` section of `Cargo.toml` of your servo repository, to tell cargo use your patched glslopt-rs.

```toml
glslopt = { path = "/path/to/your/patched/glslopt-rs/repository" }
```

This should at least allow you to compile Servo locally for development, but it does not guarantee that it won’t alter the behavior of glsl-optimizer.

Eventually, we still need to wait for the upstream fix.

Edit: add link to the patch for firefox in archlinux repository

**Comment by sagudev** [comment]
Can you push the patch to upstream glsl-optimizer: https://github.com/jamienicol/glsl-optimizer

**Comment by kkoyung** [comment]
> Can you push the patch to upstream glsl-optimizer: https://github.com/jamienicol/glsl-optimizer

I’ve just submitted a PR to the upstream repository.

**Comment by kkoyung** [comment]
The PR https://github.com/jamienicol/glsl-optimizer/pull/18 has been merged. The upstream maintainer said there will be a new release once other similar issues with C++23 and Glibc 2.43 are fixed.

Before the new release is out, for those who experience this issue when building servo, here is the workaround for building servo locally:

```bash
# Clone `glslopt-rs` repository
git clone --recurse-submodules https://github.com/jamienicol/glslopt-rs

# Checkout the latest commit of glsl-optimizer submodule
cd glslopt-rs/glsl-optimizer
git checkout master
```

Then, add the following line under `[patch.crates-io]` section of `Cargo.toml` of your servo repository.

```toml
glslopt = { path = "/path/to/the/glslopt-rs/repository/you/just/cloned" }
```

**Comment by atouchet** [comment]
glslopt was updated in #44413. Is this fixed now?

**Comment by kkoyung** [comment]
> glslopt was updated in [#44413](https://github.com/servo/servo/pull/44413). Is this fixed now?

Yes. `glslopt-rs` has just bumped the version to 0.1.13 in https://github.com/jamienicol/glslopt-rs/commit/23cc205fb3a86f82d6f0086cb8e3530c3ef390ce. We also updated our `Cargo.lock` in #44413. I tested with my Arch Linux machine, and successfully compiled servo on it.
