### PR TITLE
Upgrade to rustc 1.44.0-nightly (42abbd887 2020-04-07)

### PR DESCRIPTION
**Pull request by SimonSapin**
~Blocked on https://github.com/rust-lang/rust/issues/70280~

### CODE REVIEW

**Comment by SimonSapin** [comment]
@jdm, have you seen something like this in Xargo before?

```
error[E0463]: can't find crate for `panic_unwind`
error: aborting due to previous error
For more information about this error, try `rustc --explain E0463`.
error: could not compile `std`.
To learn more, run the command again with --verbose.
error: `"cargo" "build" "--release" "--manifest-path" "C:\\Users\\TAAD65~1\\AppData\\Local\\Temp\\xargo.HfQjqaCped9F\\Cargo.toml" "--target" "aarch64-uwp-windows-msvc" "-p" "std"` failed with exit code: Some(101)
stack backtrace:
```

**Comment by jdm** [comment]
I suspect that's caused by https://github.com/rust-lang/rust/pull/70704 and https://github.com/servo/servo/blob/master/Xargo.toml#L4-L6. We should be able to use the panic-unwind feature for aarch64 now.

**Comment by SimonSapin** [comment]
Added `features = ["panic-unwind"]`.

@bors-servo r=nox

**Comment by SimonSapin** [comment]
Never mind there are other failures.

**Comment by SimonSapin** [comment]
@bors-servo try

I’ll cancel mac-wpt to keep workers less busy.

**Comment by SimonSapin** [comment]
https://community-tc.services.mozilla.com/tasks/H9-4AvNIRXmhqwab_jIFIA/runs/0 is green, I couldn’t reproduce this segfault in `profile` crate unit tests, though I didn’t change any code to fix it ¯\_(ツ)_/¯

https://community-tc.services.mozilla.com/tasks/YQx3oICFSFilcBr1Gh7d5w/runs/0/logs/https%3A%2F%2Fcommunity-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FYQx3oICFSFilcBr1Gh7d5w%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log#L2718

**Comment by jdm** [comment]
The segfault is #23168.

**Comment by CYBAI** [comment]
servo/intermittent-failure-tracker#5

**Comment by jdm** [comment]
@bors-servo retry
Fixed the server issue

**Comment by jdm** [comment]
@bors-servo retry
* #25513
