### PR TITLE
forcetouch events

### PR DESCRIPTION
**Pull request by paulrouget**
https://developer.apple.com/library/mac/documentation/AppleApplications/Conceptual/SafariJSProgTopics/RespondingtoForceTouchEventsfromJavaScript.html

Not sure how we want to land that yet. Maybe reproduce the webkit events (as in this PR), or as touch/mousemouse events.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9811)

### CODE REVIEW

**Comment by Ms2ger** [comment]
No spec at all? Seems like a definite no.

**Comment by paulrouget** [comment]
I'll add a pref.

**Comment by paulrouget** [comment]
The events only fire if the pref `dom.forcetouch.enabled` is set.
Not sure how I should test that.

Can someone look at this and tell what needs to be done to land that?

**Comment by paulrouget** [comment]
We probably want this too: https://github.com/servo/servo/pull/10081

**Comment by mbrubeck** [comment]
The code looks good to me, with some minor comments (below).

Before I r+ this, any objections to landing this non-standard feature behind a pref and prefix? Do we need to block on #10081? Do we need a way to make "chrome-only" features?

-S-awaiting-review +S-needs-code-changes +S-needs-decision 

---

Reviewed 1 of 10 files at r1, 10 of 10 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[components/script/dom/document.rs, line 218 \[r2\]](https://reviewable.io:443/reviews/servo/servo/9811#-KDPY9chqr43KJ4QvQVW:-KDPY9chqr43KJ4QvQVX:-946367520) ([raw file](https://github.com/servo/servo/blob/656f7a8326318a336a4eec464c68cc50d0405ee7/components/script/dom/document.rs#L218)):*
Since we expect `stage` to be 0, 1, or 2, it would be nice to use an enum instead of an i64, though maybe that should go in glutin.

---

*[components/script/dom/document.rs, line 798 \[r2\]](https://reviewable.io:443/reviews/servo/servo/9811#-KDPWNZWXPZBJvJQkdSR:-KDPWNZXTBl0jjUC5yDf:338054207) ([raw file](https://github.com/servo/servo/blob/656f7a8326318a336a4eec464c68cc50d0405ee7/components/script/dom/document.rs#L798)):*
From the Safari docs, `mouseforcechanged` should be dispatched only after `mousedown` and before `mouseup`.  (I think this means it should be dispatched only if `stage > 1`).

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9811#-:-KDPXSA14goZN33eCh3J:1155790394)*

**Comment by paulrouget** [comment]
> Do we need a way to make "chrome-only" features?

Just FYI, so far, "chrome" features are: Mozbrowser API and cross-origin xhr (WIP https://github.com/servo/servo/pull/10068). Both are only available if 1) the mozbrowser pref is turned on 2) the API is used in the root pipeline.

**Comment by paulrouget** [comment]
Addressed comments.

I remove `webkitmouseforcewillbegin` for now. It's only useful if the `preventDefault()` works, which I don't think it is yet. I will implement it in a follow-up bug (and make sure browserhtml actually follow this behavior).

**Comment by mbrubeck** [comment]
@bors-servo r+

---

Reviewed 10 of 10 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9811#-:-KDV99yL-TSB1RhZnj4e:1236647940)*

**Comment by larsbergstrom** [comment]
@bors-servo retry
- infra

**Comment by paulrouget** [comment]
I think the issue was the missing `cfg(feature=window)` in `ports/glutin/window.rs`.
Changed it.

@mbrubeck can you re-r+ or delegate?

**Comment by mbrubeck** [comment]
@bors-servo r+ delegate+

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9811#-:-KDZEy3HzIPuS2cgyCof:-1205042646)*

**Comment by jdm** [comment]
```
  ▶ Unexpected subtest result in /_mozilla/mozilla/interfaces.html:
  │ FAIL [expected PASS] Interfaces exposed on the window
  │   → assert_true: If this is failing: DANGER, are you sure you want to expose the new interface ForceTouchEvent to all webpages as a property on the window? Do not make a change to this file without review from jdm or Ms2ger for that specific change! expected true got false
  │ 
  │ @http://web-platform.test:8000/_mozilla/mozilla/interfaces.html:264:1
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1381:20
  │ test@http://web-platform.test:8000/resources/testharness.js:495:9
  └ @http://web-platform.test:8000/_mozilla/mozilla/interfaces.html:258:1
```

**Comment by KiChjang** [comment]
@jdm Is that a seal of approval?

**Comment by jdm** [comment]
Yes.

**Comment by paulrouget** [comment]
I'll wait until #10081 lands.

**Comment by paulrouget** [comment]
Note to self: add `dom.forcetouch.enabled` to `resources/prefs.json`.

**Comment by paulrouget** [comment]
(rebased and added pref to prefs.json)

**Comment by paulrouget** [comment]
I'm not sure when #10081 will land. So I've updated my PR and added ForceTouchEvent to interfaces.html. This test will fail with #10081.

**Comment by paulrouget** [comment]
@bors-servo retry

infra

**Comment by paulrouget** [comment]
@bors-servo retry

infra

**Comment by larsbergstrom** [comment]
```
Tests with unexpected results:
  ▶ TIMEOUT [expected OK] /cssom-view/scrollingElement.html
  │ 
  │ ERROR:js::rust: Error at http://web-platform.test:8000/cssom-view/scrollingElement.html:14:4: URL.createObjectURL is not a function
  │ 
  │ ERROR:js::rust: Error at http://web-platform.test:8000/cssom-view/scrollingElement.html:11:6: URL.createObjectURL is not a function
  └ 

  ▶ Unexpected subtest result in /cssom-view/scrollingElement.html:
  └ NOTRUN [expected FAIL] Tests for scrollingElement

```

**Comment by jdm** [comment]
@bors-servo: retry
* #10398
