### ISSUE TITLE
Body IDL harness tests failing while interfaces appear implemented

### ISSUE THREAD

**Issue by gterzian** [servo/servo#26724]
https://github.com/servo/servo/blob/14303bd651e248e6e7a73759d622658088f9ddf1/tests/wpt/metadata/fetch/api/idlharness.any.js.ini

While `Response` and `Request` both implement the `Body` mixin(see methods like `Json`). 

Not sure why.

**Comment by jdm** [comment]
Which specific test failures in the ini file are you referring to here?

**Comment by jdm** [comment]
I tried commenting out some of the metadata entries for blob/formdata etc.
```
  FAIL Response interface: operation blob() - assert_unreached: Throws "TypeError: "this" object does not implement interface Response." instead of rejecting promise Reached unreachable code
throwOrReject/<@http://web-platform.test:8000/resources/idlharness.js:116:33
Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1977:25
throwOrReject@http://web-platform.test:8000/resources/idlharness.js:115:20
IdlInterface.prototype.do_member_operation_asserts@http://web-platform.test:8000/resources/idlharness.js:2551:26
IdlInterface.prototype.test_member_operation/<@http://web-platform.test:8000/resources/idlharness.js:2471:14
Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1977:25
IdlInterface.prototype.test_member_operation@http://web-platform.test:8000/resources/idlharness.js:2419:12
IdlInterface.prototype.test_members@http://web-platform.test:8000/resources/idlharness.js:2729:26
IdlInterface.prototype.test@http://web-platform.test:8000/resources/idlharness.js:1587:10
IdlArray.prototype.test@http://web-platform.test:8000/resources/idlharness.js:906:28
idl_test/</<@http://web-platform.test:8000/resources/idlharness.js:3470:31
  FAIL Response interface: operation formData() - assert_unreached: Throws "TypeError: "this" object does not implement interface Response." instead of rejecting promise Reached unreachable code
throwOrReject/<@http://web-platform.test:8000/resources/idlharness.js:116:33
Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1977:25
throwOrReject@http://web-platform.test:8000/resources/idlharness.js:115:20
IdlInterface.prototype.do_member_operation_asserts@http://web-platform.test:8000/resources/idlharness.js:2551:26
IdlInterface.prototype.test_member_operation/<@http://web-platform.test:8000/resources/idlharness.js:2471:14
Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1977:25
IdlInterface.prototype.test_member_operation@http://web-platform.test:8000/resources/idlharness.js:2419:12
IdlInterface.prototype.test_members@http://web-platform.test:8000/resources/idlharness.js:2729:26
IdlInterface.prototype.test@http://web-platform.test:8000/resources/idlharness.js:1587:10
IdlArray.prototype.test@http://web-platform.test:8000/resources/idlharness.js:906:28
idl_test/</<@http://web-platform.test:8000/resources/idlharness.js:3470:31
```
I _suspect_ that this is another example of a test failure caused by #26774, given those error messages.

**Comment by gterzian** [comment]
Yes looks like it would be that issue(I was referring to the various methods like `json`, `formData`, and `blob` which are implemented and still fail the harness).
