### PR TITLE
Upgrade to rustc 1.3.0-dev (fddfd089b 2015-07-10)

### LINKED ISSUE #6020: CORS check compares strings, not URL components
https://fetch.spec.whatwg.org/#cors-check includes:
> Let *origin* be the result of parsing `Access-Control-Allow-Origin` in response's header list. 
> …
> If request's origin, serialized and utf-8 encoded, is not *origin*, return failure. 

The corresponding code in Servo is in `script::cors::allow_cross_origin_request`:
```rust
        Some(&AccessControlAllowOrigin::Value(ref url)) =>
            url.scheme == req.origin.scheme &&
            url.host() == req.origin.host() &&
            url.port() == req.origin.port(),
```

But comparing (scheme, host, port) components of parsed URL is not necessarily the same as comparing a serialized URL to a string. Maybe `AccessControlAllowOrigin::Value`’s value should be a `String` rather than a parsed `Url`?

### PR DESCRIPTION
**Pull request by SimonSapin**
Depends on https://github.com/jgraham/webdriver-rust/pull/12.

Fixes #6020.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6591)

### CODE REVIEW

**Comment by pcwalton** [comment]
Looks good to me, once upstream is merged feel free to land.

**Comment by SimonSapin** [comment]
@bors-servo r=pcwalton

(Re-ran `./mach update-cargo -p webdriver` and `./mach update-cargo -p hyper` now that https://github.com/jgraham/webdriver-rust/pull/12 is merged.)

**Comment by SimonSapin** [comment]
```
ld: warning: directory not found for option '-L/Users/servo/buildbot/slave/mac2/build/ports/cef/lib/x86_64-apple-darwin'
ld: warning: directory not found for option '-L/Users/servo/.rust/lib/x86_64-apple-darwin'
duplicate symbol _TaskBasicInfoVirtualSize in:
    /var/folders/sd/sks3rs2s3pb9bdrg9ldf9d5w0000gp/T/rustc.pqY5S1Luk7Wa/libtask_info-6ccbc3024e2756cc.rlib(r-task_info-task_info.o)
    /var/folders/sd/sks3rs2s3pb9bdrg9ldf9d5w0000gp/T/rustc.pqY5S1Luk7Wa/libtask_info-6ccbc3024e2756cc.rlib(r-1-task_info-task_info.o)
duplicate symbol _TaskBasicInfoResidentSize in:
    /var/folders/sd/sks3rs2s3pb9bdrg9ldf9d5w0000gp/T/rustc.pqY5S1Luk7Wa/libtask_info-6ccbc3024e2756cc.rlib(r-task_info-task_info.o)
    /var/folders/sd/sks3rs2s3pb9bdrg9ldf9d5w0000gp/T/rustc.pqY5S1Luk7Wa/libtask_info-6ccbc3024e2756cc.rlib(r-1-task_info-task_info.o)
duplicate symbol __Z8SkDebugfPKcz in:
    /var/folders/sd/sks3rs2s3pb9bdrg9ldf9d5w0000gp/T/rustc.pqY5S1Luk7Wa/libazure-f792f70de9cc89e8.rlib(r-skia-SkDebug_stdio.o)
    /var/folders/sd/sks3rs2s3pb9bdrg9ldf9d5w0000gp/T/rustc.pqY5S1Luk7Wa/libazure-f792f70de9cc89e8.rlib(r-1-skia-SkDebug_stdio.o)
ld: 3 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by pcwalton** [comment]
<pcwalton> SimonSapin: sometimes the Skia one is the result of Skia and Azure not being compiled with the same -D preprocessor flags
    <pcwalton> SimonSapin: I've seen that sort of thing happen with SK_DEBUG being set to 1 in skia-sys and 0 in rust-azure, or vice-versa

**Comment by pcwalton** [comment]
Maybe we have multiple versions of packages. Check the `Cargo.lock`?

**Comment by SimonSapin** [comment]
The only crates duplicated in `Cargo.lock` are `android_glue` and `bitflags`. I couldn’t reproduce locally on a mac. Let’s see if this is intermittent.

@bors-servo retry

**Comment by SimonSapin** [comment]
Ah, I missed that this is in `build-cef`. I can reproduce locally.

**Comment by larsbergstrom** [comment]
Hrm. This is super confusing because when you do a build-cef, the only new things compiled are the `servo` crate (with a different set of features enabled) and the `embedding` crate.

**Comment by larsbergstrom** [comment]
Happens even on a clean build of CEF - https://pastebin.mozilla.org/8839475

**Comment by larsbergstrom** [comment]
@alexcrichton Have you ever seen something like this? We're getting duplicate symbols reported during link from a couple of crates (Skia and task-info) when we build a shared library (the CEF embedding stuff) but not when we build a binary (the final `servo` binary) - despite the fact that these crates are *not* rebuilt and we share target directories.

If I `nm -g` libtaskinfo, I do get what appears to be two copies of the symbol:
```
./deps/libtask_info-4f894c0f5635aa99.rlib
                 U _TaskBasicInfoVirtualSize
0000000000000000 T _TaskBasicInfoVirtualSize
0000000000000000 T _TaskBasicInfoVirtualSize
```

Working on it, but this is currently blocking our rustup, so if you have any ideas, they'd be appreciated :-)

**Comment by alexcrichton** [comment]
I suspect this is caused by https://github.com/rust-lang/rust/pull/26869 (the `-force_load` flag for OSX archives), although it looks like the `task_info` library may be getting linked twice? For example these two object filenames show up:

```
r-task_info-task_info.o
r-1-task_info-task_info.o
```

I believe that [this is linking the library once](https://github.com/servo/servo/blob/master/support/rust-task_info/build.rs#L10) and [this is linking it again](https://github.com/servo/servo/blob/master/support/rust-task_info/src/task_basic_info.rs#L33), so if you remove the `#[link]` annotation you should be good to go.

Perhaps the skia bug is also somewhat related?

**Comment by larsbergstrom** [comment]
@alexcrichton That fixed it for the task info - thanks a ton!

I suspect it's a little more complicated for skia, as the static lib is pulled in via `#[link]` lines in multiple places in rust-azure plus one in the actual skia repo, but I should (hopefully) be able to track down what we should really be doing. There are hacks on top of hacks dating back to partial attempts to stand something up on Android, where linking/loading was... iffy... for a while.

**Comment by alexcrichton** [comment]
The pattern that I would suggest is the similar `foo` and `foo-sys` crates that crates.io has. For example if you have skia bindings I'd put them in the `skia` crate but the FFI definitions are in the `skia-sys` crate. Additionally, the `#[link]` (or linage via a build script) is only present for the `skia-sys` crate, so `skia-sys` is the one source of truth for linking the native library. That way the rust-azure crate could depend on `skia-sys` to be sure to link the library but doesn't necessarily need to pull in all the bindings of `skia`

**Comment by larsbergstrom** [comment]
@alexcrichton Yeah, I think most of our hacks are also to preserve link order, which is really finicky here. e.g., we need to link in fontconfig *after* skia or the skia bindings to FC functions will be unresolved.

**Comment by metajack** [comment]
@alexcrichton I think that's what we tried to achieve, but some of this is pre-Cargo legacy. We'll clean it up after this round of Rust upgrades and see if we run into further issues.

**Comment by SimonSapin** [comment]
I’ll rebase.

**Comment by SimonSapin** [comment]
I force-pushed my rebase of bbed054 without thinking of fetching first, so I overwrote any change made since. Sorry! @larsbergstrom I think you had some, could you push your local branch again? Either force-push and I can rebase again, or push to another branch and I can cherry-pick your changes.

Also, it looks like rust-layers now need to be updated for changes in Skia: https://travis-ci.org/servo/rust-layers/jobs/70484266

**Comment by mrobinson** [comment]
I've added the commit that gets rust-layers up to date, as well as reworking the code to work properly with it.

**Comment by pcwalton** [comment]
LGTM.
