### ISSUE TITLE
libsignpost breaks the build on less recent macOS

### ISSUE THREAD

**Issue by jdm** [servo/servo#13745]
```
  = note: Undefined symbols for architecture x86_64:
  "_kdebug_trace", referenced from:
      signpost::start::hb7f2e093303f09e1 in libsignpost-8f8922b25b81c62b.rlib(signpost-8f8922b25b81c62b.0.o)
      signpost::end::hde99872f3d5e79c5 in libsignpost-8f8922b25b81c62b.rlib(signpost-8f8922b25b81c62b.0.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)


error: aborting due to previous error

error: Could not compile `servo`.
```

**Comment by jdm** [comment]
I've worked around this locally by overriding signpost with a clone that doesn't use those methods. It would be nice to get a real fix for this somehow; quick googling didn't give me any clue if this is something that should be linked explicitly or whether kdebug_trace simply doesn't exist on older versions like 10.9.5.

**Comment by kaksmet** [comment]
From what I can gather `kdebug_trace` was introduced in `xnu-2782.10.72`, which corresponds to OS X 10.10.2.

**Comment by pcwalton** [comment]
I think it was introduced in Yosemite. Argh, sorry about that.

**Comment by pcwalton** [comment]
acrichto says you can't cfg it off based on versions. I guess the best thing to do is to check at runtime and dynamically import.

**Comment by SimonSapin** [comment]
I can still reproduce this issue (i.e. I can’t build Servo on this macbook) after upgrading to 10.12.1 and then running `./mach clean`.

Am I missing some dependency?

**Comment by pcwalton** [comment]
This is annoying. I now think we should just call the syscall directly. On unsupported OS versions it should harmlessly fail with `ENOSYS` at runtime.

**Comment by SimonSapin** [comment]
I managed to get a build after:

* Installing full XCode 8.1 instead of XCode command line tools 5.1.1 (which I didn’t find how to update)
* Reinstalling Homebrew, my install of it got broken somehow
* Following OpenSSL-related instructions at https://github.com/servo/servo/#on-os-x--1011-el-capitan-you-also-have-to-install-openssl
* `./mach clean`

For all I know, it’s possible that upgrading OS X was not necessary, only XCode.

**Comment by nox** [comment]
Seems like this can be closed.
