### ISSUE TITLE
Android build fails

### ISSUE THREAD

**Issue by dati91** [servo/servo#13154]
The current android build is failing with the following issues:
- [x] libfontconfig error 
- [x] android_start! macro
- [x] backtrace
- [x] linker error 1
- [x] linker error 2

_The libfontconfig error_

```
--- stderr
configure: WARNING: using cross tools not prefixed with host triplet
configure: error: 
*** expat is required. or try to use --enable-libxml2
make: *** [servo/target/arm-linux-androideabi/debug/build/servo-fontconfig-sys-0c6dc76cced7fb8b/out/Makefile] Error 1
thread 'main' panicked at 'assertion failed: Command::new("make").args(&["-R", "-f",
                            "makefile.cargo"]).status().unwrap().success()', servo/.cargo/registry/src/github.com-1ecc6299db9ec823/servo-fontconfig-sys-4.0.1/build.rs:17
```

This will be solved with `servo-fontconfig-sys-4.0.2`. Fixed with [this](https://github.com/servo/libfontconfig/commit/6beaba4d6bafaef09a350af84a7c3dd9b7b82fff).

_The `android_start!` macro_

```
error: macro undefined: 'android_start!'
   --> main.rs:265:1
    |
265 | android_start!(main);
    | ^^^^^^^^^^^^^
```

This is related to the [android-rs-glue](https://github.com/tomaka/android-rs-glue) update (`0.1.3 -> 0.2.0`). Which was introduced in [this](https://github.com/servo/servo/pull/12893) pr.

If we comment out the macro, we can move to our next error.

_Backtrace in unguarded code_

```
error[E0432]: unresolved import `backtrace::Backtrace`
  --> main.rs:37:5
   |
37 | use backtrace::Backtrace;
   |     ^^^^^^^^^^^^^^^^^^^^ Maybe a missing `extern crate backtrace`?
```

This was introduced with [this](https://github.com/servo/servo/pull/12657) pr.
If we revert this, we will get to the linking phase.

_Linker Error 1_

```
arm-linux-androideabi-gcc: error: : No such file or directory
```

This is caused by [this](https://github.com/servo/servo/blob/master/components/servo/fake-ld.sh#L13) line, the `"${LDFLAGS-}"` is empty.
If we get rid of that, we will arrive to our last obstacle.

_Linker Error 2_

```
servo/.cargo/registry/src/github.com-1ecc6299db9ec823/android_glue-0.2.0/src/lib.rs:111: error: undefined reference to 'cargo_apk_injected_glue_write_log'
servo/.cargo/registry/src/github.com-1ecc6299db9ec823/android_glue-0.2.0/src/lib.rs:103: error: undefined reference to 'cargo_apk_injected_glue_get_native_window'
servo/.cargo/registry/src/github.com-1ecc6299db9ec823/android_glue-0.2.0/src/lib.rs:75: error: undefined reference to 'cargo_apk_injected_glue_add_sender'
servo/.cargo/registry/src/github.com-1ecc6299db9ec823/android_glue-0.2.0/src/lib.rs:82: error: undefined reference to 'cargo_apk_injected_glue_set_multitouch'
servo/.cargo/registry/src/github.com-1ecc6299db9ec823/android_glue-0.2.0/src/lib.rs:103: error: undefined reference to 'cargo_apk_injected_glue_get_native_window'
servo/target/arm-linux-androideabi/debug/deps/libservo.rlib(android_native_app_glue.o):android_native_app_glue.c:function android_app_entry: error: undefined reference to 'android_main'
servo/.cargo/git/checkouts/gaol-c3a1e33941376f84/master/platform/linux/namespace.rs:193: error: undefined reference to 'unshare'
servo/.cargo/git/checkouts/gaol-c3a1e33941376f84/master/platform/linux/namespace.rs:249: error: undefined reference to 'unshare'
servo/.cargo/git/checkouts/rust-mozjs-8611526964119dd6/master/src/jsglue.cpp:724: error: undefined reference to 'malloc_usable_size'
android-ndk/sources/cxx-stl/llvm-libc++/libcxx/include/ios:524: error: undefined reference to 'std::__ndk1::ios_base::clear(unsigned int)'
android-ndk/sources/cxx-stl/llvm-libc++/libcxx/include/ios:668: error: undefined reference to 'std::__ndk1::ios_base::init(void*)'
android-ndk/sources/cxx-stl/llvm-libc++/libcxx/include/ios:734: error: undefined reference to 'std::__ndk1::ios_base::getloc() const'
android-ndk/sources/cxx-stl/llvm-libc++/libcxx/include/__locale:174: error: undefined reference to 'std::__ndk1::locale::use_facet(std::__ndk1::locale::id&) const'
android-ndk/sources/cxx-stl/llvm-libc++/libcxx/include/ios:734: error: undefined reference to 'std::__ndk1::locale::~locale()'
android-ndk/sources/cxx-stl/llvm-libc++/libcxx/include/ios:661: error: undefined reference to 'std::__ndk1::ios_base::~ios_base()'
android-ndk/sources/cxx-stl/llvm-libc++/libcxx/include/ios:524: error: undefined reference to 'std::__ndk1::ios_base::clear(unsigned int)'
android-ndk/sources/cxx-stl/llvm-libc++/libcxx/include/ios:668: error: undefined reference to 'std::__ndk1::ios_base::init(void*)'
android-ndk/sources/cxx-stl/llvm-libc++/libcxx/include/ios:734: error: undefined reference to 'std::__ndk1::ios_base::getloc() const'
android-ndk/sources/cxx-stl/llvm-libc++/libcxx/include/__locale:174: error: undefined reference to 'std::__ndk1::locale::use_facet(std::__ndk1::locale::id&) const'
android-ndk/sources/cxx-stl/llvm-libc++/libcxx/include/ios:734: error: undefined reference to 'std::__ndk1::locale::~locale()'
android-ndk/sources/cxx-stl/llvm-libc++/libcxx/include/ios:661: error: undefined reference to 'std::__ndk1::ios_base::~ios_base()'
android-ndk/sources/cxx-stl/llvm-libc++/libcxx/include/ios:524: error: undefined reference to 'std::__ndk1::ios_base::clear(unsigned int)'
android-ndk/sources/cxx-stl/llvm-libc++/libcxx/include/ios:524: error: undefined reference to 'std::__ndk1::ctype<char>::id'
android-ndk/sources/cxx-stl/llvm-libc++/libcxx/include/ios:661: error: undefined reference to 'std::__ndk1::ios_base::~ios_base()'
android-ndk/sources/cxx-stl/llvm-libc++/libcxx/include/ios:661: error: undefined reference to 'std::__ndk1::ios_base::~ios_base()'
android-ndk/sources/cxx-stl/llvm-libc++/libcxx/include/streambuf:220: error: undefined reference to 'std::__ndk1::locale::~locale()'
android-ndk/sources/cxx-stl/llvm-libc++/libcxx/include/streambuf:220: error: undefined reference to 'std::__ndk1::locale::~locale()'
android-ndk/sources/cxx-stl/llvm-libc++/libcxx/include/__locale:174: error: undefined reference to 'std::__ndk1::locale::use_facet(std::__ndk1::locale::id&) const'
android-ndk/sources/cxx-stl/llvm-libc++/libcxx/include/fstream:947: error: undefined reference to 'std::__ndk1::codecvt<char, char, mbstate_t>::id'
android-ndk/sources/cxx-stl/llvm-libc++/libcxx/include/streambuf:370: error: undefined reference to 'std::__ndk1::locale::locale()'
android-ndk/sources/cxx-stl/llvm-libc++/libcxx/include/streambuf:238: error: undefined reference to 'std::__ndk1::locale::locale(std::__ndk1::locale const&)'
android-ndk/sources/cxx-stl/llvm-libc++/libcxx/include/__locale:166: error: undefined reference to 'std::__ndk1::locale::has_facet(std::__ndk1::locale::id&) const'
android-ndk/sources/cxx-stl/llvm-libc++/libcxx/include/streambuf:238: error: undefined reference to 'std::__ndk1::locale::locale(std::__ndk1::locale const&)'
android-ndk/sources/cxx-stl/llvm-libc++/libcxx/include/__locale:174: error: undefined reference to 'std::__ndk1::locale::use_facet(std::__ndk1::locale::id&) const'
android-ndk/sources/cxx-stl/llvm-libc++/libcxx/include/fstream:272: error: undefined reference to 'std::__ndk1::codecvt<char, char, mbstate_t>::id'
android-ndk/sources/cxx-stl/llvm-libc++/libcxx/include/ios:524: error: undefined reference to 'std::__ndk1::ios_base::clear(unsigned int)'
android-ndk/sources/cxx-stl/llvm-libc++/libcxx/include/istream:275: error: undefined reference to 'std::__ndk1::ios_base::getloc() const'
android-ndk/sources/cxx-stl/llvm-libc++/libcxx/include/iterator:846: error: undefined reference to 'std::__ndk1::ctype<char>::id'
collect2: error: ld returned 1 exit status
```

Which is related to the `android_glue` update mentioned above.

**Comment by aneeshusa** [comment]
Thanks for the detective work! I think we can get rid of `$LDFLAGS` entirely but I'm not sure, see #12562.

**Comment by larsbergstrom** [comment]
I am working on this.

**Comment by larsbergstrom** [comment]
I've uploaded some initial changes to use the different stdlib here:
https://github.com/servo/servo/tree/android_libstd

**Comment by vmx** [comment]
A new failure got introduced. You'll hit it as first one, before the "libfontconfig error" one.

```
error[E0432]: unresolved import `libc::AF_NETLINK`
  --> /home/vmx/src/rust/servo/servo/.cargo/git/checkouts/gaol-c3a1e33941376f84/master/platform/linux/seccomp.rs:24:46
   |
24 | use libc::{self, AF_INET, AF_INET6, AF_UNIX, AF_NETLINK};
   |                                              ^^^^^^^^^^ no `AF_NETLINK` in `libc`
```

It got introduced by commit https://github.com/servo/gaol/commit/039661b3cdf756648a8cc755b61d39c4d89501ca.

Going back to commit https://github.com/servo/gaol/commit/8c789101c0fb13d1613781d2c7cbe65076b5b924 works and the build advances to the libconfig error.

**Comment by mmatyas** [comment]
After some hacks, I've managed to build it; I'll clean my patches up a bit and post additional PRs soon. I have some problems with creating the APK currently, but I'll test it on a device as soon as I can.

**Comment by mmatyas** [comment]
Here are the remaining patches -- I didn't send PRs for them because some of them are hacks (fontsan, libfontconfig), some may be Servo-specific (libheartbeats), and the backtrace build fix may not work on real device. These patches work with @larsbergstrom's patch, using NDK v12 (because v13 doesn't build at all, probably due to GCC/Clang changes).

https://gist.github.com/mmatyas/cb9eac611b6ce350158e4421651bf4dd

**Comment by mmatyas** [comment]
An interesting thing is that while `--sysroot` and related paths is set by Lars' python code, it doesn't work for libfontconfig and fontsan. Also, I've used `gnu-libstdc++` for fontsan, because using  `llvm-libc++`, I got `undefined _Exit` errors.

**Comment by mmatyas** [comment]
I've found the bug in `fontsan` and `libfontconfig`, the C/CXX flags were not captured properly.

**Comment by mmatyas** [comment]
Current status:

```
I/ActivityManager( 3195): Start proc com.mozilla.servo for activity com.mozilla.servo/.MainActivity: pid=5899 uid=10068 gids={50068, 3003, 1028, 1015, 1023, 3002, 3001}
I/servo_wrapper( 5899): Loading the NativeActivity
D/dalvikvm( 5899): Trying to load lib /data/app-lib/com.mozilla.servo-1/libmain.so 0x418ed508
E/dalvikvm( 5899): dlopen("/data/app-lib/com.mozilla.servo-1/libmain.so") failed: dlopen failed: cannot locate symbol "cargo_apk_injected_glue_write_log" referenced by "libmain.so"...
W/dalvikvm( 5899): Exception Ljava/lang/UnsatisfiedLinkError; thrown while initializing Lcom/mozilla/servo/MainActivity;
W/dalvikvm( 5899): Class init failed in newInstance call (Lcom/mozilla/servo/MainActivity;)
D/AndroidRuntime( 5899): Shutting down VM
W/dalvikvm( 5899): threadid=1: thread exiting with uncaught exception (group=0x4162eba8)
I/InputDispatcher( 3195): Dropping event because there is no touchable window at (454, 380).
E/AndroidRuntime( 5899): FATAL EXCEPTION: main
E/AndroidRuntime( 5899): Process: com.mozilla.servo, PID: 5899
E/AndroidRuntime( 5899): java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "cargo_apk_injected_glue_write_log" referenced by "libmain.so"...
E/AndroidRuntime( 5899): 	at java.lang.Runtime.loadLibrary(Runtime.java:364)
E/AndroidRuntime( 5899): 	at java.lang.System.loadLibrary(System.java:526)
E/AndroidRuntime( 5899): 	at com.mozilla.servo.MainActivity.<clinit>(MainActivity.java:16)
E/AndroidRuntime( 5899): 	at java.lang.Class.newInstanceImpl(Native Method)
E/AndroidRuntime( 5899): 	at java.lang.Class.newInstance(Class.java:1208)
E/AndroidRuntime( 5899): 	at android.app.Instrumentation.newActivity(Instrumentation.java:1061)
E/AndroidRuntime( 5899): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2101)
E/AndroidRuntime( 5899): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
E/AndroidRuntime( 5899): 	at android.app.ActivityThread.access$800(ActivityThread.java:135)
E/AndroidRuntime( 5899): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
E/AndroidRuntime( 5899): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 5899): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 5899): 	at android.app.ActivityThread.main(ActivityThread.java:5001)
E/AndroidRuntime( 5899): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 5899): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 5899): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
E/AndroidRuntime( 5899): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
E/AndroidRuntime( 5899): 	at dalvik.system.NativeStart.main(Native Method)
W/ActivityManager( 3195):   Force finishing activity com.mozilla.servo/.MainActivity
I/InputDispatcher( 3195): Dropping event because there is no touchable window at (455, 383)
```

**Comment by dati91** [comment]
My guess would be that the [android-rs-glue](https://github.com/tomaka/android-rs-glue) update (0.1.3 -> 0.2.0) still requires some adjusting.
Maybe you could ask the owner of that repo to help you out, if you get stuck.

**Comment by mmatyas** [comment]
cc @tomaka

**Comment by tomaka** [comment]
Hmm I'm surprised that Servo has this problem.
I asked multiple times on #servo for feedback about the changes in android-rs-glue. Since I was only getting vague answers and since Servo has their own fork of glutin, I decided to push the changes anyway. I didn't expect that Servo didn't test their Android build.

Anyway, in android-rs-glue 0.1 the functions required by glutin to initialize the stuff (like the one in your error) are located in the glue library itself. This is why the `android_start!` macro is required.
In android-rs-glue 0.2, these functions are in an external library that is injected by the `cargo-apk` utility.

The clean way to compile is to use the `cargo-apk` utility (as described in android-rs-glue's README), but with some trickery you could also use your own building system.

**Comment by tomaka** [comment]
If you choose to go the hacky route, the codes to compile with Servo are:
- This one, directly in the executable: https://github.com/tomaka/android-rs-glue/blob/master/cargo-apk/glue_obj.rs
- This one as a library: https://github.com/tomaka/android-rs-glue/tree/master/cargo-apk/injected-glue

**Comment by larsbergstrom** [comment]
Yeah, as we mentioned at the time, back during the changeover to the new packaging method since it wasn't possible to override the manifest and other build files, we needed to clone that piece. It's no big deal - I've assumed that as Servo on Android continued to grow it would be unreasonable to expect the builder to support all of our wonky scenarios.

Thanks for the tips on the files to include!

FWIW, the glutin fork only has about 6 changes (supporting embedding, touch events, and high-performance window flags on macOS), all of which I plan to upstream. It wasn't possible to do so cleanly in the past, but it appears most of the architectural hooks needed to do so more elegantly are there now so we may have something r+'able.

Also, we haven't been able to test Android because SpiderMonkey changed their version of lib C++, which had a massive impact across the whole dependency ecosystem (both on build rules and library usage). The fine folks from Szeged are helping sort this out, because it's been a real challenge to focus on Android with the big push across the team to support Servo-in-Firefox.

**Comment by larsbergstrom** [comment]
Pushed another update to my branch. I think we're good to go except for https://github.com/libheartbeats/heartbeats-simple-sys/pull/17

**Comment by mmatyas** [comment]
Could someone reopen this issue? It's been closed by the bot.

**Comment by mmatyas** [comment]
Current status:
```
dlopen("/data/app-lib/com.mozilla.servo-1/libmain.so") failed: dlopen failed: cannot locate symbol "__cxa_end_cleanup" referenced by "libmain.so"...
```

**Comment by dati91** [comment]
[This](http://stackoverflow.com/questions/9226513/linker-errors-in-android-ndk-undefined-reference-to-cxa-end-cleanup) looks promising.

**Comment by mmatyas** [comment]
Linking with `-lc++` fixed most of the dynamic symbols, except only one (`__cxa_type_match`); I'll try linking with a different libc++.

**Comment by mmatyas** [comment]
Current status: `E/AndroidRuntime(16415): java.lang.UnsatisfiedLinkError: dlopen failed: could not load library "libc++_shared.so" needed by "libmain.so"; caused by library "libc++_shared.so" not found`

**Comment by mmatyas** [comment]
IT'S ALIVE! Behold, the pinnacle of browser technology:

![screen](https://cloud.githubusercontent.com/assets/4354863/19727985/f67a8684-9b91-11e6-9914-ca1775cbd1bd.png)

**Comment by mmatyas** [comment]
@larsbergstrom when do you plan to land your patch?

**Comment by dati91** [comment]
One additional note: You can only build android with java 7 and below.

The build.xml used via ant sets the default target/source to 1.5, which is not supported in java 9 anymore. But You can define an ant.properties file where you can redefine these properties.

If you get `unsupported class file version 52.0` error, you should downgrade your buildtools to 23. You can achieve this by adding `sdk.buildtools=23.0.3` to your local.properties. (and this version should be installed in your sdk)

With Java 8, you will probably get a `java.lang.RuntimeException: Exception parsing classes` with the dex-ing. This will go away if you downgrade to Java 7. Setting the target/source to 1.7 won't solve it, because the is an external jar, which will be compiled with the default javac version.

**Comment by larsbergstrom** [comment]
Almost there! Just have:
```
note: /home/servo/android/ndk/r10e/android-ndk-r10e/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9/../../../../arm-linux-androideabi/bin/ld.gold: error: cannot find -lc++
```

This is probably a problem with a bad (old?) NDK installation on the machines.

**Comment by mmatyas** [comment]
Here are the remaining, **very ugly** hacks I had to do to make it run: https://gist.github.com/mmatyas/50ee6f4c65c74a034eb5753a5d33060b

This makes Servo run and produce the gray screen. `logcat` shows this: https://gist.github.com/mmatyas/50ee6f4c65c74a034eb5753a5d33060b#file-log. It does not crash, nor produces any more errors.

**Comment by mmatyas** [comment]
So, I thought maybe the glue code wasn't injected/set up properly, so I replaced the current Android build system with cargo-apk, but that didn't help either. Then I noticed producing ~crazy~ random input for several seconds causes Servo to actually do something: it starts loading the shaders, and crashes there.

The first shader error I've got was a simple `no default precision defined for variable 'sCache'` which I've fixed by adding `precision mediump sampler2DArray;` to `shared.glsl`. Now I get
```
D/RustAndroidGlueStdouterr( 6470): Failed to compile shader: "/sdcard/servo/shaders/ps_rectangle_clip.vs.glsl"
D/RustAndroidGlueStdouterr( 6470): 0:18: S0001: Type mismatch, cannot convert from 'ivec2' to 'vec2'
```
but I'm not sure how to fix that. I don't really see any `ivec2` around there, or in the related functions.

My changes so far are here: https://github.com/mmatyas/servo/tree/androidglueupdate, and here: https://github.com/mmatyas/android-rs-glue/tree/servo. Clone `android-rs-glue` under `support/android/` to make it work.

**Comment by larsbergstrom** [comment]
cc @glennw for ideas about the failure to compile the shaders on Android

**Comment by mmatyas** [comment]
Since the Android build, in general, works, and this issue is quite long already, I've opened #14568 to deal with the runtime issues on Android. The shader issues got fixed, and at the moment, Servo runs on Android, but has display issues.
