### PR TITLE
Add secure connection start

### LINKED ISSUE #21268: PerformanceResourceTiming: secureConnectionStart
In components/net/http_loader.rs::http_fetch we need to set secure_connection_start (if we're using a persistent connection). Otherwise, we can probably use components/net/connector.rs for this

On getting, the secureConnectionStart attribute MUST return as follows:

1. The same value as fetchStart, if a persistent connection [RFC7230] is used or the resource is retrieved from relevant application caches or local resources.
2. The time immediately before the user agent starts the handshake process to secure the current connection, if a secure transport is used and the last non-redirected fetch of the resource passes the timing allow check algorithm.
3. zero, otherwise.

Spec: https://w3c.github.io/resource-timing/#dom-performanceresourcetiming-secureconnectionstart

### PR DESCRIPTION
**Pull request by tomasdivito**
Implementing `secure_connection_start` as well as we can, this is related to #21268 

We are setting the value as well as we can since we don't have a way to know if we are currently using a secure transport or where the handshake before the connection is done as the spec says on the step 15 [https://w3c.github.io/resource-timing/#sec-process](https://w3c.github.io/resource-timing/#sec-process)

Regarding the Timing Allow Check, that's being done on another PR by another person which will take care of setting the rest of the values on `PerformaceResourceTiming` to Zero and prevent them to set them any other way.

I'm currently setting the `secure_connection_time` using `precise_time_ms()` as the `connection_start` and `connection_end` are set that way... but other attributes inside `PerformanceResourceTiming` are set using `precise_time

Another thing, the issue talks about setting `redirect_start` but I'm not really sure if it's related, if so I can look up into that too... I might have just read and thought it was all about secure connection start.

---
- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [ ] These changes fix #21268 

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because ___

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23990)

### CODE REVIEW

**Comment by jdm** [comment]
I updated the issue to remove the reference to redirect_start.

File: components/net_traits/lib.rs [hunk 1]
```diff
@@ -476,6 +477,7 @@ pub enum ResourceAttribute {
     FetchStart,
     ConnectStart(u64),
     ConnectEnd(u64),
+    SecureConnectionStart(u64),
```
Comment (jdm) [inline components/net_traits/lib.rs]: No need to pass a value here - like many other values, we can default to precise_time_ns().

File: components/net_traits/lib.rs [hunk 2]
```diff
@@ -527,6 +530,7 @@ impl ResourceFetchTiming {
             ResourceAttribute::FetchStart => self.fetch_start = precise_time_ns(),
             ResourceAttribute::ConnectStart(val) => self.connect_start = val,
             ResourceAttribute::ConnectEnd(val) => self.connect_end = val,
+            ResourceAttribute::SecureConnectionStart(val) => self.secure_connection_start = val,
```
Comment (jdm) [inline components/net_traits/lib.rs]: We should set this to precise_time_ns() instead.

**Review by jdm — CHANGES_REQUESTED** [review]
We will also need to update components/script/dom/webidls/PerformanceResourceTiming.webidl and components/script/dom/performanceresourcetiming.rs. Exposing the new DOM APIs should cause some test results in `./mach test-wpt tests/wpt/web-platform-tests/resource-timing/` to change (https://github.com/servo/servo/blob/master/tests/wpt/README.md#updating-test-expectations explains how to update the expected results).

**Comment by tomasdivito** [comment]
I'll be working on making the required changes to the currently failing tests.

**Comment by jdm** [comment]
Still working on this @tomasdivito?

**Comment by tomasdivito** [comment]
@jdm Sorry, got really busy with university, I'll try to make the tests work tomorrow and probably ask some questions if that's ok, sorry for not updating!

**Comment by jdm** [comment]
This needs a `./mach fmt`, but also there is a build failure since #23873:
```
error[E0201]: duplicate definitions with name `SecureConnectionStart`:
   --> components\script\dom\performanceresourcetiming.rs:256:5
    |
196 | /     fn SecureConnectionStart(&self) -> DOMHighResTimeStamp {
197 | |         Finite::wrap(self.secure_connection_start)
198 | |     }
    | |_____- previous definition of `SecureConnectionStart` here
...
256 | /     fn SecureConnectionStart(&self) -> DOMHighResTimeStamp {
257 | |         Finite::wrap(self.secure_connection_start)
258 | |     }
    | |_____^ duplicate definition
error: aborting due to previous error
For more information about this error, try `rustc --explain E0201`.
```

**Comment by tomasdivito** [comment]
@jdm when running the web platform tests like you suggested

`./mach test-wpt tests/wpt/web-platform-tests/resource-timing/` I'm getting different errors and timeouts that sometimes occur, and sometimes not, and I'm not sure if this can be related to my computer (I'm currently using a macbook air 2015 which is not that powerful, but I would had assumed that it would not matter much or any... but maybe I'm wrong?) 

An example of the output I'm getting for the last run:

```
Ran 71 tests finished in 307.0 seconds.
  • 42 ran as expected. 0 tests skipped.
  • 28 tests timed out unexpectedly
  • 1 tests had unexpected subtest results
```

while previously I got
```
Ran 71 tests finished in 314.0 seconds.
  • 33 ran as expected. 0 tests skipped.
  • 38 tests timed out unexpectedly
```

**Comment by jdm** [comment]
This looks good! Please squash the commits together into one and remove the "draft" marking for this PR, and then it will be ready to merge.

**Comment by jdm** [comment]
@bors-servo r+
Thanks!
