### ISSUE TITLE
macOS ld considers libscript-*.rlib to be invalid

### ISSUE THREAD

**Issue by CYBAI** [servo/servo#25550]
Cannot build Servo with latest master (2a594821ba) on macOS 10.14.6

(This is my first time to see this kind of compilation error 🤔 I've tried to run `./mach clean` but it didn't help :/)

Check the error message [in this gist](https://gist.github.com/CYBAI/190f432efdf1d0398c502337ec22234f) 👈

**Comment by jdm** [comment]
I suspect that the important part of that output is:
```
  = note: ld: warning: ignoring file /Users/cybai/codespace/mozilla/servo/target/debug/deps/libscript-0dfa8adb95c0400d.rlib, file was built for archive which is not the architecture being linked (x86_64): /Users/cybai/codespace/mozilla/servo/target/debug/deps/libscript-0dfa8adb95c0400d.rlib
```
I'm not sure what to make of it. Could you gist the complete build output of `./mach build -d -vv`?

**Comment by jdm** [comment]
Also, I wonder if this is a regression from https://github.com/servo/servo/pull/25536. Try reverting `850f52c32778ac0ad0ea48580a4b7006970f5c94` and see if that helps?

**Comment by CYBAI** [comment]
@jdm I tried to run `git bisect` locally and the first bad commit is not `850f52c32778ac0ad0ea48580a4b7006970f5c94` 👀

```
→ git bisect bad
7d5048f8852df0de2a0a86cb16e2a54f493b6e7c is the first bad commit
commit 7d5048f8852df0de2a0a86cb16e2a54f493b6e7c
Author: Mátyás Mustoha <matyas.mustoha@h-lab.eu>
Date:   Thu Jan 16 12:34:45 2020 +0100

    Add support for WebGL2 uniform matrix operations

    Adds support for the `uniformMatrix[234]x[234]fv` WebGL2 functions.

    See: https://www.khronos.org/registry/webgl/specs/latest/2.0/#3.7.8

 Cargo.lock                                         |   4 +-
 components/canvas/Cargo.toml                       |   2 +-
 components/canvas/webgl_thread.rs                  |  60 ++++++
 components/canvas_traits/webgl.rs                  |  12 ++
 components/script/dom/webgl2renderingcontext.rs    | 221 ++++++++++++++++++++-
 components/script/dom/webglrenderingcontext.rs     |  70 +++----
 .../dom/webidls/WebGL2RenderingContext.webidl      |  34 ++--
 .../dom/webidls/WebGLRenderingContext.webidl       |   9 +-
 .../meta/conformance2/context/methods-2.html.ini   |  70 +++----
 .../uniforms/gl-uniform-arrays-sub-source.html.ini |  77 -------
 10 files changed, 369 insertions(+), 190 deletions(-)
 delete mode 100644 tests/wpt/webgl/meta/conformance2/uniforms/gl-uniform-arrays-sub-source.html.ini
```

Besides, I updated [the gist](https://gist.github.com/CYBAI/190f432efdf1d0398c502337ec22234f) with `./mach build -d -vv` (the updated one is run without `./mach clean` 👀)

**Comment by NeverHappened** [comment]
Got same error on MacOS 10.15.2 (Catalina):
`= note: ld: warning: ignoring file /servo/target/debug/deps/libscript-4041fea49bf91c89.rlib, building for macOS-x86_64 but attempting to link with file built for unknown-unsupported file format ( 0x21 0x3C 0x61 0x72 0x63 0x68 0x3E 0x0A 0x2F 0x53 0x59 0x4D 0x36 0x34 0x2F 0x20 )`

**Comment by jdm** [comment]
Is there any difference if you do a release build?

**Comment by NeverHappened** [comment]
Release build works without any errors

**Comment by jdm** [comment]
This appears to be mac-specific. I'm on 10.14.6 as well and haven't observed this problem for reasons that are unclear to me.

**Comment by CYBAI** [comment]
Will it be related to llvm version 🤔? 

My llvm version:

```
→ llvm-gcc --version
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by paulrouget** [comment]
0650fc3199 compiles. Add this patch triggers the link issue. I need to be **3** enum fields:

```
diff --git a/components/canvas/webgl_thread.rs b/components/canvas/webgl_thread.rs
index d536b52d0b..c2dfcc279b 100644
--- a/components/canvas/webgl_thread.rs
+++ b/components/canvas/webgl_thread.rs
@@ -1873,6 +1873,7 @@ impl WebGLImpl {
                 offset as isize,
                 size as isize,
             ),
+            _ => {}
         }
 
         // If debug asertions are enabled, then check the error state.
diff --git a/components/canvas_traits/webgl.rs b/components/canvas_traits/webgl.rs
index 077a2e737b..cb9d4ccc74 100644
--- a/components/canvas_traits/webgl.rs
+++ b/components/canvas_traits/webgl.rs
@@ -474,6 +474,9 @@ pub enum WebGLCommand {
     GetUniformFloat4(WebGLProgramId, i32, WebGLSender<[f32; 4]>),
     GetUniformFloat9(WebGLProgramId, i32, WebGLSender<[f32; 9]>),
     GetUniformFloat16(WebGLProgramId, i32, WebGLSender<[f32; 16]>),
+    GetUniformFloat3x2(WebGLProgramId, i32, WebGLSender<[f32; 3 * 2]>),
+    GetUniformFloat3x2(WebGLProgramId, i32, WebGLSender<[f32; 3 * 4]>),
+    GetUniformFloat3x2(WebGLProgramId, i32, WebGLSender<[f32; 4 * 2]>),
     GetUniformBlockIndex(WebGLProgramId, String, WebGLSender<u32>),
     GetUniformIndices(WebGLProgramId, Vec<String>, WebGLSender<Vec<u32>>),
     GetActiveUniforms(WebGLProgramId, Vec<u32>, u32, WebGLSender<Vec<i32>>), 
```

**Comment by eddyb** [comment]
> `= note: ld: warning: ignoring file /servo/target/debug/deps/libscript-4041fea49bf91c89.rlib, building for macOS-x86_64 but attempting to link with file built for unknown-unsupported file format ( 0x21 0x3C 0x61 0x72 0x63 0x68 0x3E 0x0A 0x2F 0x53 0x59 0x4D 0x36 0x34 0x2F 0x20 )`

For the record, those bytes correspond to this string: `"!<arch>\n/SYM64/ "`.
I remember seeing that sort of thing in LLVM sources, I think it's a hack used to encode various miscellaneous information in an `ar` archive.

It's likely the output of `llvm-ar tv libscript-*.rlib` (or maybe just `ar`?) would be useful, btw.

**Comment by yodaldevoid** [comment]
@paulrouget Does compilation break when adding those three enum variants with those specific fields or any three enum variants?

**Comment by jdm** [comment]
After being unable to reproduce the problem with llvm 6 on 10.14, I have successfully reproduced the problem with llvm 9.

**Comment by paulrouget** [comment]
Funny thing:

Doesn’t compile:

```
+    GetUniformFloat3x2(WebGLProgramId, i32, WebGLSender<[f32; 3 * 2]>),                                                          
+    GetUniformFloat3x4(WebGLProgramId, i32, WebGLSender<[f32; 3 * 4]>),                                                          
+    GetUniformFloat4x2(WebGLProgramId, i32, WebGLSender<[f32; 4 * 2]>),      
```

Compiles:

```
+    GetUniformFloat3x2(WebGLProgramId, i32, WebGLSender<[f32; 3 * 2]>),                                                          
+    GetUniformFloat3x4(WebGLProgramId, i32, WebGLSender<[f32; 3 * 2]>),                                                          
+    GetUniformFloat4x2(WebGLProgramId, i32, WebGLSender<[f32; 3 * 2]>),      
```

Looking at the `ar` output, the first line differs:

```
==> ar.doesnt-works <==
---------       0/0      19578750 Jan  1 01:00 1970 /SYM64/
==> ar.works <==
---------       0/0      19578752 Jan  1 01:00 1970 __.SYMDEF
```

Could this happen because the size of the rlib reached 4Gb?

**Comment by paulrouget** [comment]
Size change:

```
# works
> ls -l ./target/debug/deps/libscript-652a3ed15b7acd06.rlib
4282598440 ./target/debug/deps/libscript-652a3ed15b7acd06.rlib      

# doesn’t work
> ls -l ./target/debug/deps/libscript-652a3ed15b7acd06.rlib
4323269602 ./target/debug/deps/libscript-652a3ed15b7acd06.rlib  
```

**Comment by eddyb** [comment]
> Could this happen because the size of the rlib reached 4Gb?

Makes sense, would explain the `64`, LLVM must be switching to that format by necessity.

Knowing this you should be able to repro with just something like `dd if=/dev/zero of=foo bs=1M count=4096` and then trying to archive that with `llvm-ar` (I don't know what the system `ar` can do)

There might not be any way to make this actually work, there's a high chance that LLVM is right and Apple is wrong.

In that case, Servo might need to somehow switch to `lld` on macOS, if that is even an option.

Or maybe we can "just" turn off `SYM64` emission on macOS for the rare cases that cross the 4GiB limit, which may work with only performance losses as a side-effect.

cc @alexcrichton @michaelwoerister

**Comment by nox** [comment]
https://opensource.apple.com/source/ld64/ld64-450.3/src/ld/InputFiles.cpp.auto.html

```c++
const char* InputFiles::fileArch(const uint8_t* p, unsigned len)
{
	const char* result = mach_o::relocatable::archName(p);
	if ( result != NULL  )
		 return result;

    result = mach_o::dylib::archName(p);
    if ( result != NULL  )
		return result;

	result = lto::archName(p, len);
	if ( result != NULL  )
		 return result;
	
	if ( strncmp((const char*)p, "!<arch>\n", 8) == 0 )
		return "archive";
	
	char *unsupported = (char *)malloc(128);
	strcpy(unsupported, "unsupported file format (");
	for (unsigned i=0; i<len && i < 16; i++) {
		char buf[8];
		sprintf(buf, " 0x%02X", p[i]);
		strcat(unsupported, buf);
	}
	strcat(unsupported, " )");
	return unsupported;
}
```

Is this not the ld we are using? Shouldn't this function return `"archive"` if given `"!<arch>\n/SYM64/ "`?

**Comment by nox** [comment]
Does macOS even understand `/SYM64/`? A quick search on the Intertubes seem to say that it should be `__.SYMDEF_64`.

**Comment by nox** [comment]
https://github.com/llvm-mirror/llvm/blob/ee4faac758c1a772c62539f5bff3944b75a97b18/lib/Object/ArchiveWriter.cpp#L315-L322

Is our LLVM thinking macOS is not BSD-like?

**Comment by nox** [comment]
https://github.com/llvm-mirror/llvm/blob/742beb6d7db253a3fbbdcd398f0fa1dfd9fc82e6/lib/Object/ArchiveWriter.cpp#L574-L582

AFAIK what happens is that we end up with a kind of `K_BSD`, and then this snippet means we switch to `K_GNU64` instead of `K_DARWIN64`.

**Comment by nox** [comment]
Also I'm out for lunch right now but I think we can set `SYM64_THRESHOLD` to 1 to force it to switch to a 64-bit symbol table and trigger the bug we are discussing here with a way smaller rlib file.

https://github.com/llvm-mirror/llvm/blob/742beb6d7db253a3fbbdcd398f0fa1dfd9fc82e6/lib/Object/ArchiveWriter.cpp#L569

**Comment by nox** [comment]
Ok, I made a new Cargo project with:

```rust
// lib.rs

pub fn main() {
    println!("Hello, world!");
}
```

```rust
// main.rs

fn main() {
    sym64crash::main()
}
```

Then I ran `SYM64_THRESHOLD=1 cargo run` and got:

```
   Compiling sym64crash v0.1.0 (/Users/nox/src/sym64crash)
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-m64" "-L" "/Users/nox/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib" "/Users/nox/src/sym64crash/target/debug/deps/sym64crash-dba30d3c9d1afba2.1shyi59cethbq6v.rcgu.o" "/Users/nox/src/sym64crash/target/debug/deps/sym64crash-dba30d3c9d1afba2.3im92gp0w3cu86nu.rcgu.o" "/Users/nox/src/sym64crash/target/debug/deps/sym64crash-dba30d3c9d1afba2.3kefkhkvggp8wuo3.rcgu.o" "/Users/nox/src/sym64crash/target/debug/deps/sym64crash-dba30d3c9d1afba2.9px6degf2j3xfde.rcgu.o" "/Users/nox/src/sym64crash/target/debug/deps/sym64crash-dba30d3c9d1afba2.si0l8nqczsdv9x6.rcgu.o" "-o" "/Users/nox/src/sym64crash/target/debug/deps/sym64crash-dba30d3c9d1afba2" "/Users/nox/src/sym64crash/target/debug/deps/sym64crash-dba30d3c9d1afba2.33jxq6f7m54ib5n3.rcgu.o" "-Wl,-dead_strip" "-nodefaultlibs" "-L" "/Users/nox/src/sym64crash/target/debug/deps" "-L" "/Users/nox/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib" "/Users/nox/src/sym64crash/target/debug/deps/libsym64crash-6ab5a9224f093771.rlib" "/Users/nox/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libstd-ec578e0d01ad5d6e.rlib" "/Users/nox/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libpanic_unwind-5412e5af11009a97.rlib" "/Users/nox/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libhashbrown-03db0718fbd4a443.rlib" "/Users/nox/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/librustc_std_workspace_alloc-8df90fdde44531fa.rlib" "/Users/nox/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libbacktrace-080b75c76cf389d3.rlib" "/Users/nox/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libbacktrace_sys-954947c96c071ed1.rlib" "/Users/nox/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/librustc_demangle-9a1775bac6aabe20.rlib" "/Users/nox/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libunwind-71147793b4cdc412.rlib" "/Users/nox/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libcfg_if-9fc81eecc6136c9a.rlib" "/Users/nox/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/liblibc-4b64712313317864.rlib" "/Users/nox/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/liballoc-1bcd644d1289b2fb.rlib" "/Users/nox/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/librustc_std_workspace_core-16c65b3b16ee989d.rlib" "/Users/nox/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libcore-7dd67903be10326a.rlib" "/Users/nox/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libcompiler_builtins-b5923fb6eca9603a.rlib" "-lSystem" "-lresolv" "-lc" "-lm"
  = note: ld: warning: ignoring file /Users/nox/src/sym64crash/target/debug/deps/libsym64crash-6ab5a9224f093771.rlib, file was built for archive which is not the architecture being linked (x86_64): /Users/nox/src/sym64crash/target/debug/deps/libsym64crash-6ab5a9224f093771.rlib
          Undefined symbols for architecture x86_64:
            "sym64crash::main::h7fee38d057326a14", referenced from:
                sym64crash::main::h130da61e786d8f8e in sym64crash-dba30d3c9d1afba2.3im92gp0w3cu86nu.rcgu.o
          ld: symbol(s) not found for architecture x86_64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)


error: aborting due to previous error

error: could not compile `sym64crash`.
```

**Comment by nox** [comment]
@alexcrichton Eddy told me to talk to you.

```diff
diff --git i/src/librustc_codegen_llvm/llvm/ffi.rs w/src/librustc_codegen_llvm/llvm/ffi.rs
index b07214fdc03..397fcfa4246 100644
--- i/src/librustc_codegen_llvm/llvm/ffi.rs
+++ w/src/librustc_codegen_llvm/llvm/ffi.rs
@@ -456,6 +456,7 @@ pub enum ArchiveKind {
     Other,
     K_GNU,
     K_BSD,
+    K_DARWIN,
     K_COFF,
 }
 
diff --git i/src/librustc_codegen_llvm/llvm/mod.rs w/src/librustc_codegen_llvm/llvm/mod.rs
index 57815933af0..3cb5c23a446 100644
--- i/src/librustc_codegen_llvm/llvm/mod.rs
+++ w/src/librustc_codegen_llvm/llvm/mod.rs
@@ -75,6 +75,7 @@ impl FromStr for ArchiveKind {
         match s {
             "gnu" => Ok(ArchiveKind::K_GNU),
             "bsd" => Ok(ArchiveKind::K_BSD),
+            "darwin" => Ok(ArchiveKind::K_DARWIN),
             "coff" => Ok(ArchiveKind::K_COFF),
             _ => Err(()),
         }
diff --git i/src/librustc_target/spec/apple_base.rs w/src/librustc_target/spec/apple_base.rs
index f7551aa768d..811fcea6965 100644
--- i/src/librustc_target/spec/apple_base.rs
+++ w/src/librustc_target/spec/apple_base.rs
@@ -26,7 +26,7 @@ pub fn opts() -> TargetOptions {
         has_rpath: true,
         dll_prefix: "lib".to_string(),
         dll_suffix: ".dylib".to_string(),
-        archive_format: "bsd".to_string(),
+        archive_format: "darwin".to_string(),
         pre_link_args: LinkArgs::new(),
         has_elf_tls: version >= (10, 7),
         abi_return_struct_as_int: true,
diff --git i/src/rustllvm/ArchiveWrapper.cpp w/src/rustllvm/ArchiveWrapper.cpp
index dd0111d3f2c..e16b6187e99 100644
--- i/src/rustllvm/ArchiveWrapper.cpp
+++ w/src/rustllvm/ArchiveWrapper.cpp
@@ -38,6 +38,7 @@ enum class LLVMRustArchiveKind {
   Other,
   GNU,
   BSD,
+  DARWIN,
   COFF,
 };
 
@@ -47,6 +48,8 @@ static Archive::Kind fromRust(LLVMRustArchiveKind Kind) {
     return Archive::K_GNU;
   case LLVMRustArchiveKind::BSD:
     return Archive::K_BSD;
+  case LLVMRustArchiveKind::DARWIN:
+    return Archive::K_DARWIN;
   case LLVMRustArchiveKind::COFF:
     return Archive::K_COFF;
   default:
```

Does that seem like an acceptable fix to you? Should I instead piggy back the `is_like_osx` target bit? Or the linker flavour?

**Comment by eddyb** [comment]
@nox What does `clang` do? `DARWIN` or `BSD`?

**Comment by alexcrichton** [comment]
That patch seems reasonable to me, although I agree with @eddyb that we should probably match clang. I suspect that `darwin` was added after we implemented all the archive stuff in rustc, and `clang` probably uses the `darwin` kind to LLVM as well.

**Comment by nox** [comment]
I'll make a patch today then, thanks.
