### ISSUE TITLE
WebGPU CTS fail due to bad serviceworker impl

### ISSUE THREAD

**Issue by sagudev** [servo/servo#36657]
```
ERROR [expected OK] /_webgpu/webgpu/cts.https.html?q=webgpu:api,operation,command_buffer,copyTextureToTexture:zero_sized:*
  │   → navigator.serviceWorker.getRegistrations is not a function
  │ 
  │ unregisterAllServiceWorkers@https://web-platform.test:8443/_webgpu/webgpu/common/runtime/helper/test_worker.js:13:32
  └ @https://web-platform.test:8443/_webgpu/webgpu/common/runtime/helper/test_worker.js:25:3
```

is caused by https://github.com/servo/servo/pull/36335, which enables all experimental prefs (including serviceworkers).
