### ISSUE TITLE
Windows build is broken with VS 15.9.4

### ISSUE THREAD

**Issue by ydogus** [servo/servo#22636]
Hello,
I believe this is the same problem as https://github.com/servo/servo/issues/22476 but happening locally. It started after updating my Visual Studio to the latest version 15.9.4.

> --- stderr
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\yvals_core.h:294:5: error: STL1000: Unexpected compiler version, expected Clang 7 or newer.
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\yvals_core.h:294:5: error: STL1000: Unexpected compiler version, expected Clang 7 or newer., err: true

**Comment by grahamh** [comment]
Hi,

Also getting this exact error with VS15.9.4. This is my first build so no experience with previous versions of VS.

**Comment by jdm** [comment]
Ooh, that does sound like a good lead! I'll try that on the appveyor build and see what happens.

**Comment by jdm** [comment]
Appveyor successfully built with that removed: https://github.com/servo/servo/compare/jdm-patch-33?expand=1

**Comment by UK992** [comment]
Why not update LLVM to 7.0.0? it successfully build with VS 15.6.7.

**Comment by jdm** [comment]
I think GStreamer is a bit different because it's dynamically linked; most of our other dependencies are statically linked. The GStreamer installer does some special setup to make it work as expected.

**Comment by asajeffrey** [comment]
@jdm The windows llvm installer is a thin `.exe` wrapper round an archive (`7z` IIRC). On the Mac in the Chicago office, "The Unarchiver" opened and uncompressed it. The default directory names it unpacks into need fixed, after which I packed it into a `.zip` archive.

**Comment by jdm** [comment]
Thanks for the suggestions @BeatButton and @UK992! #22756 should fix this issue.
